/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish_api.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchBase implements Serializable {

    private static final long serialVersionUID = -1616359667;

    private String    batchCode;
    private String    authCode;
    private Timestamp createDate;
    private Boolean   status;
    private Integer   count;
    private Integer   processingTime;
    private String    msg;
    private String    type;

    public BatchBase() {}

    public BatchBase(BatchBase value) {
        this.batchCode = value.batchCode;
        this.authCode = value.authCode;
        this.createDate = value.createDate;
        this.status = value.status;
        this.count = value.count;
        this.processingTime = value.processingTime;
        this.msg = value.msg;
        this.type = value.type;
    }

    public BatchBase(
        String    batchCode,
        String    authCode,
        Timestamp createDate,
        Boolean   status,
        Integer   count,
        Integer   processingTime,
        String    msg,
        String    type
    ) {
        this.batchCode = batchCode;
        this.authCode = authCode;
        this.createDate = createDate;
        this.status = status;
        this.count = count;
        this.processingTime = processingTime;
        this.msg = msg;
        this.type = type;
    }

    public String getBatchCode() {
        return this.batchCode;
    }

    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode;
    }

    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getProcessingTime() {
        return this.processingTime;
    }

    public void setProcessingTime(Integer processingTime) {
        this.processingTime = processingTime;
    }

    public String getMsg() {
        return this.msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BatchBase (");

        sb.append(batchCode);
        sb.append(", ").append(authCode);
        sb.append(", ").append(createDate);
        sb.append(", ").append(status);
        sb.append(", ").append(count);
        sb.append(", ").append(processingTime);
        sb.append(", ").append(msg);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
