/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish_api.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Campaigns implements Serializable {

    private static final long serialVersionUID = -975929361;

    private String     id;
    private Timestamp  date;
    private BigDecimal spend;
    private String     currencyCode;
    private Integer    impressions;
    private String     productId;
    private String     dateKey;
    private String     authCode;

    public Campaigns() {}

    public Campaigns(Campaigns value) {
        this.id = value.id;
        this.date = value.date;
        this.spend = value.spend;
        this.currencyCode = value.currencyCode;
        this.impressions = value.impressions;
        this.productId = value.productId;
        this.dateKey = value.dateKey;
        this.authCode = value.authCode;
    }

    public Campaigns(
        String     id,
        Timestamp  date,
        BigDecimal spend,
        String     currencyCode,
        Integer    impressions,
        String     productId,
        String     dateKey,
        String     authCode
    ) {
        this.id = id;
        this.date = date;
        this.spend = spend;
        this.currencyCode = currencyCode;
        this.impressions = impressions;
        this.productId = productId;
        this.dateKey = dateKey;
        this.authCode = authCode;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Timestamp getDate() {
        return this.date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public BigDecimal getSpend() {
        return this.spend;
    }

    public void setSpend(BigDecimal spend) {
        this.spend = spend;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public Integer getImpressions() {
        return this.impressions;
    }

    public void setImpressions(Integer impressions) {
        this.impressions = impressions;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getDateKey() {
        return this.dateKey;
    }

    public void setDateKey(String dateKey) {
        this.dateKey = dateKey;
    }

    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Campaigns (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(spend);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(impressions);
        sb.append(", ").append(productId);
        sb.append(", ").append(dateKey);
        sb.append(", ").append(authCode);

        sb.append(")");
        return sb.toString();
    }
}
