/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish_api.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Variation implements Serializable {

    private static final long serialVersionUID = 705133046;

    private String     productId;
    private String     parentSku;
    private String     variationId;
    private String     sku;
    private String     size;
    private String     color;
    private BigDecimal price;
    private BigDecimal shipping;
    private String     currencycode;
    private Integer    inventory;
    private Boolean    status;
    private String     imageUrl;
    private String     authCode;

    public Variation() {}

    public Variation(Variation value) {
        this.productId = value.productId;
        this.parentSku = value.parentSku;
        this.variationId = value.variationId;
        this.sku = value.sku;
        this.size = value.size;
        this.color = value.color;
        this.price = value.price;
        this.shipping = value.shipping;
        this.currencycode = value.currencycode;
        this.inventory = value.inventory;
        this.status = value.status;
        this.imageUrl = value.imageUrl;
        this.authCode = value.authCode;
    }

    public Variation(
        String     productId,
        String     parentSku,
        String     variationId,
        String     sku,
        String     size,
        String     color,
        BigDecimal price,
        BigDecimal shipping,
        String     currencycode,
        Integer    inventory,
        Boolean    status,
        String     imageUrl,
        String     authCode
    ) {
        this.productId = productId;
        this.parentSku = parentSku;
        this.variationId = variationId;
        this.sku = sku;
        this.size = size;
        this.color = color;
        this.price = price;
        this.shipping = shipping;
        this.currencycode = currencycode;
        this.inventory = inventory;
        this.status = status;
        this.imageUrl = imageUrl;
        this.authCode = authCode;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getParentSku() {
        return this.parentSku;
    }

    public void setParentSku(String parentSku) {
        this.parentSku = parentSku;
    }

    public String getVariationId() {
        return this.variationId;
    }

    public void setVariationId(String variationId) {
        this.variationId = variationId;
    }

    public String getSku() {
        return this.sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getShipping() {
        return this.shipping;
    }

    public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    public String getCurrencycode() {
        return this.currencycode;
    }

    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }

    public Integer getInventory() {
        return this.inventory;
    }

    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Variation (");

        sb.append(productId);
        sb.append(", ").append(parentSku);
        sb.append(", ").append(variationId);
        sb.append(", ").append(sku);
        sb.append(", ").append(size);
        sb.append(", ").append(color);
        sb.append(", ").append(price);
        sb.append(", ").append(shipping);
        sb.append(", ").append(currencycode);
        sb.append(", ").append(inventory);
        sb.append(", ").append(status);
        sb.append(", ").append(imageUrl);
        sb.append(", ").append(authCode);

        sb.append(")");
        return sb.toString();
    }
}
