/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tanggod.github.io.config.database.repository.wish.Indexes;
import tanggod.github.io.config.database.repository.wish.Keys;
import tanggod.github.io.config.database.repository.wish.Wish;
import tanggod.github.io.config.database.repository.wish.tables.records.JzmPurchaseOrderRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JzmPurchaseOrder extends TableImpl<JzmPurchaseOrderRecord> {

    private static final long serialVersionUID = -1900227145;

    /**
     * The reference instance of <code>wish.jzm_purchase_order</code>
     */
    public static final JzmPurchaseOrder JZM_PURCHASE_ORDER = new JzmPurchaseOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JzmPurchaseOrderRecord> getRecordType() {
        return JzmPurchaseOrderRecord.class;
    }

    /**
     * The column <code>wish.jzm_purchase_order.id</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.create_date</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.product_sku</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, String> PRODUCT_SKU = createField("product_sku", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.sku_code</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, String> SKU_CODE = createField("sku_code", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.code</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.count</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.size</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, String> SIZE = createField("size", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.max_count</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, Integer> MAX_COUNT = createField("max_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.is_generate</code>. 是否生成采购单
     */
    public final TableField<JzmPurchaseOrderRecord, Boolean> IS_GENERATE = createField("is_generate", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "是否生成采购单");

    /**
     * The column <code>wish.jzm_purchase_order.warehouse_order_code</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, String> WAREHOUSE_ORDER_CODE = createField("warehouse_order_code", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.jzm_purchase_order.is_close</code>.
     */
    public final TableField<JzmPurchaseOrderRecord, Boolean> IS_CLOSE = createField("is_close", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>wish.jzm_purchase_order</code> table reference
     */
    public JzmPurchaseOrder() {
        this(DSL.name("jzm_purchase_order"), null);
    }

    /**
     * Create an aliased <code>wish.jzm_purchase_order</code> table reference
     */
    public JzmPurchaseOrder(String alias) {
        this(DSL.name(alias), JZM_PURCHASE_ORDER);
    }

    /**
     * Create an aliased <code>wish.jzm_purchase_order</code> table reference
     */
    public JzmPurchaseOrder(Name alias) {
        this(alias, JZM_PURCHASE_ORDER);
    }

    private JzmPurchaseOrder(Name alias, Table<JzmPurchaseOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private JzmPurchaseOrder(Name alias, Table<JzmPurchaseOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wish.WISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.JZM_PURCHASE_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JzmPurchaseOrderRecord> getPrimaryKey() {
        return Keys.KEY_JZM_PURCHASE_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JzmPurchaseOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<JzmPurchaseOrderRecord>>asList(Keys.KEY_JZM_PURCHASE_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrder as(String alias) {
        return new JzmPurchaseOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrder as(Name alias) {
        return new JzmPurchaseOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JzmPurchaseOrder rename(String name) {
        return new JzmPurchaseOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JzmPurchaseOrder rename(Name name) {
        return new JzmPurchaseOrder(name, null);
    }
}
