/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tanggod.github.io.config.database.repository.wish.Indexes;
import tanggod.github.io.config.database.repository.wish.Keys;
import tanggod.github.io.config.database.repository.wish.Wish;
import tanggod.github.io.config.database.repository.wish.tables.records.TiktokOrderRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TiktokOrder extends TableImpl<TiktokOrderRecord> {

    private static final long serialVersionUID = 870328192;

    /**
     * The reference instance of <code>wish.tikTok_order</code>
     */
    public static final TiktokOrder TIKTOK_ORDER = new TiktokOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TiktokOrderRecord> getRecordType() {
        return TiktokOrderRecord.class;
    }

    /**
     * The column <code>wish.tikTok_order.id</code>.
     */
    public final TableField<TiktokOrderRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>wish.tikTok_order.order_id</code>.
     */
    public final TableField<TiktokOrderRecord, String> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>wish.tikTok_order.receiver</code>.
     */
    public final TableField<TiktokOrderRecord, String> RECEIVER = createField("receiver", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>wish.tikTok_order.contact_details</code>.
     */
    public final TableField<TiktokOrderRecord, String> CONTACT_DETAILS = createField("contact_details", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>wish.tikTok_order.shipping_address</code>.
     */
    public final TableField<TiktokOrderRecord, String> SHIPPING_ADDRESS = createField("shipping_address", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>wish.tikTok_order.sync</code>.
     */
    public final TableField<TiktokOrderRecord, Boolean> SYNC = createField("sync", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>wish.tikTok_order</code> table reference
     */
    public TiktokOrder() {
        this(DSL.name("tikTok_order"), null);
    }

    /**
     * Create an aliased <code>wish.tikTok_order</code> table reference
     */
    public TiktokOrder(String alias) {
        this(DSL.name(alias), TIKTOK_ORDER);
    }

    /**
     * Create an aliased <code>wish.tikTok_order</code> table reference
     */
    public TiktokOrder(Name alias) {
        this(alias, TIKTOK_ORDER);
    }

    private TiktokOrder(Name alias, Table<TiktokOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private TiktokOrder(Name alias, Table<TiktokOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wish.WISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TIKTOK_ORDER_1, Indexes.TIKTOK_ORDER_2, Indexes.TIKTOK_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TiktokOrderRecord> getPrimaryKey() {
        return Keys.KEY_TIKTOK_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TiktokOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<TiktokOrderRecord>>asList(Keys.KEY_TIKTOK_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TiktokOrder as(String alias) {
        return new TiktokOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TiktokOrder as(Name alias) {
        return new TiktokOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TiktokOrder rename(String name) {
        return new TiktokOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TiktokOrder rename(Name name) {
        return new TiktokOrder(name, null);
    }
}
