/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tanggod.github.io.config.database.repository.wish.Indexes;
import tanggod.github.io.config.database.repository.wish.Keys;
import tanggod.github.io.config.database.repository.wish.Wish;
import tanggod.github.io.config.database.repository.wish.tables.records.WishProductSalesMonitorDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishProductSalesMonitorData extends TableImpl<WishProductSalesMonitorDataRecord> {

    private static final long serialVersionUID = 706915224;

    /**
     * The reference instance of <code>wish.wish_product_sales_monitor_data</code>
     */
    public static final WishProductSalesMonitorData WISH_PRODUCT_SALES_MONITOR_DATA = new WishProductSalesMonitorData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WishProductSalesMonitorDataRecord> getRecordType() {
        return WishProductSalesMonitorDataRecord.class;
    }

    /**
     * The column <code>wish.wish_product_sales_monitor_data.id</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.auth_code</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> AUTH_CODE = createField("auth_code", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.product_id</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.main_image</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> MAIN_IMAGE = createField("main_image", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.parent_sku</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> PARENT_SKU = createField("parent_sku", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.variant_sku</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> VARIANT_SKU = createField("variant_sku", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.variant_id</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> VARIANT_ID = createField("variant_id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.price</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.shipping</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Double> SHIPPING = createField("shipping", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.localized_currency_code</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> LOCALIZED_CURRENCY_CODE = createField("localized_currency_code", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.size</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> SIZE = createField("size", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.color</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, String> COLOR = createField("color", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.localized_price</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Double> LOCALIZED_PRICE = createField("localized_price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.localized_shipping</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Double> LOCALIZED_SHIPPING = createField("localized_shipping", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.date_uploaded</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Timestamp> DATE_UPLOADED = createField("date_uploaded", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.inventory_status</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Boolean> INVENTORY_STATUS = createField("inventory_status", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.inventory_change</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Integer> INVENTORY_CHANGE = createField("inventory_change", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.create_date</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.number_sold</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Integer> NUMBER_SOLD = createField("number_sold", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>wish.wish_product_sales_monitor_data.number_saves</code>.
     */
    public final TableField<WishProductSalesMonitorDataRecord, Integer> NUMBER_SAVES = createField("number_saves", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>wish.wish_product_sales_monitor_data</code> table reference
     */
    public WishProductSalesMonitorData() {
        this(DSL.name("wish_product_sales_monitor_data"), null);
    }

    /**
     * Create an aliased <code>wish.wish_product_sales_monitor_data</code> table reference
     */
    public WishProductSalesMonitorData(String alias) {
        this(DSL.name(alias), WISH_PRODUCT_SALES_MONITOR_DATA);
    }

    /**
     * Create an aliased <code>wish.wish_product_sales_monitor_data</code> table reference
     */
    public WishProductSalesMonitorData(Name alias) {
        this(alias, WISH_PRODUCT_SALES_MONITOR_DATA);
    }

    private WishProductSalesMonitorData(Name alias, Table<WishProductSalesMonitorDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private WishProductSalesMonitorData(Name alias, Table<WishProductSalesMonitorDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wish.WISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_AUTH_CODE, Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_CREATE_DATE, Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_DATE_UPLOADED, Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_INVENTORY_STATUS, Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_PARENT_SKU, Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_PRIMARY, Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_PRODUCT_ID, Indexes.WISH_PRODUCT_SALES_MONITOR_DATA_VARIANT_SKU);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WishProductSalesMonitorDataRecord> getPrimaryKey() {
        return Keys.KEY_WISH_PRODUCT_SALES_MONITOR_DATA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WishProductSalesMonitorDataRecord>> getKeys() {
        return Arrays.<UniqueKey<WishProductSalesMonitorDataRecord>>asList(Keys.KEY_WISH_PRODUCT_SALES_MONITOR_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductSalesMonitorData as(String alias) {
        return new WishProductSalesMonitorData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductSalesMonitorData as(Name alias) {
        return new WishProductSalesMonitorData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WishProductSalesMonitorData rename(String name) {
        return new WishProductSalesMonitorData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WishProductSalesMonitorData rename(Name name) {
        return new WishProductSalesMonitorData(name, null);
    }
}
