/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tanggod.github.io.config.database.repository.wish.Indexes;
import tanggod.github.io.config.database.repository.wish.Keys;
import tanggod.github.io.config.database.repository.wish.Wish;
import tanggod.github.io.config.database.repository.wish.tables.records.WishKeywordSearchRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishKeywordSearch extends TableImpl<WishKeywordSearchRecord> {

    private static final long serialVersionUID = 1457848644;

    /**
     * The reference instance of <code>wish.wish_keyword_search</code>
     */
    public static final WishKeywordSearch WISH_KEYWORD_SEARCH = new WishKeywordSearch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WishKeywordSearchRecord> getRecordType() {
        return WishKeywordSearchRecord.class;
    }

    /**
     * The column <code>wish.wish_keyword_search.id</code>.
     */
    public final TableField<WishKeywordSearchRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>wish.wish_keyword_search.cookie</code>.
     */
    public final TableField<WishKeywordSearchRecord, String> COOKIE = createField("cookie", org.jooq.impl.SQLDataType.VARCHAR(5000).nullable(false), this, "");

    /**
     * The column <code>wish.wish_keyword_search.access_token</code>.
     */
    public final TableField<WishKeywordSearchRecord, String> ACCESS_TOKEN = createField("access_token", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * Create a <code>wish.wish_keyword_search</code> table reference
     */
    public WishKeywordSearch() {
        this(DSL.name("wish_keyword_search"), null);
    }

    /**
     * Create an aliased <code>wish.wish_keyword_search</code> table reference
     */
    public WishKeywordSearch(String alias) {
        this(DSL.name(alias), WISH_KEYWORD_SEARCH);
    }

    /**
     * Create an aliased <code>wish.wish_keyword_search</code> table reference
     */
    public WishKeywordSearch(Name alias) {
        this(alias, WISH_KEYWORD_SEARCH);
    }

    private WishKeywordSearch(Name alias, Table<WishKeywordSearchRecord> aliased) {
        this(alias, aliased, null);
    }

    private WishKeywordSearch(Name alias, Table<WishKeywordSearchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wish.WISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WISH_KEYWORD_SEARCH_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WishKeywordSearchRecord> getPrimaryKey() {
        return Keys.KEY_WISH_KEYWORD_SEARCH_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WishKeywordSearchRecord>> getKeys() {
        return Arrays.<UniqueKey<WishKeywordSearchRecord>>asList(Keys.KEY_WISH_KEYWORD_SEARCH_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishKeywordSearch as(String alias) {
        return new WishKeywordSearch(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishKeywordSearch as(Name alias) {
        return new WishKeywordSearch(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WishKeywordSearch rename(String name) {
        return new WishKeywordSearch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WishKeywordSearch rename(Name name) {
        return new WishKeywordSearch(name, null);
    }
}
