/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tanggod.github.io.config.database.repository.wish.Wish;
import tanggod.github.io.config.database.repository.wish.tables.records.WishCountryShippingRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishCountryShipping extends TableImpl<WishCountryShippingRecord> {

    private static final long serialVersionUID = -472538590;

    /**
     * The reference instance of <code>wish.wish_country_shipping</code>
     */
    public static final WishCountryShipping WISH_COUNTRY_SHIPPING = new WishCountryShipping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WishCountryShippingRecord> getRecordType() {
        return WishCountryShippingRecord.class;
    }

    /**
     * The column <code>wish.wish_country_shipping.product_id</code>.
     */
    public final TableField<WishCountryShippingRecord, String> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>wish.wish_country_shipping.price</code>.
     */
    public final TableField<WishCountryShippingRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>wish.wish_country_shipping.country_code</code>.
     */
    public final TableField<WishCountryShippingRecord, String> COUNTRY_CODE = createField("country_code", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>wish.wish_country_shipping</code> table reference
     */
    public WishCountryShipping() {
        this(DSL.name("wish_country_shipping"), null);
    }

    /**
     * Create an aliased <code>wish.wish_country_shipping</code> table reference
     */
    public WishCountryShipping(String alias) {
        this(DSL.name(alias), WISH_COUNTRY_SHIPPING);
    }

    /**
     * Create an aliased <code>wish.wish_country_shipping</code> table reference
     */
    public WishCountryShipping(Name alias) {
        this(alias, WISH_COUNTRY_SHIPPING);
    }

    private WishCountryShipping(Name alias, Table<WishCountryShippingRecord> aliased) {
        this(alias, aliased, null);
    }

    private WishCountryShipping(Name alias, Table<WishCountryShippingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Wish.WISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishCountryShipping as(String alias) {
        return new WishCountryShipping(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishCountryShipping as(Name alias) {
        return new WishCountryShipping(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WishCountryShipping rename(String name) {
        return new WishCountryShipping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WishCountryShipping rename(Name name) {
        return new WishCountryShipping(name, null);
    }
}
