/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.system.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.system.tables.Product;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record8<String, String, String, String, Timestamp, Timestamp, String, Boolean> {

    private static final long serialVersionUID = -811444613;

    /**
     * Setter for <code>system.product.product_id</code>.
     */
    public void setProductId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>system.product.product_id</code>.
     */
    public String getProductId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>system.product.sku_name</code>.
     */
    public void setSkuName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>system.product.sku_name</code>.
     */
    public String getSkuName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>system.product.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>system.product.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>system.product.extra_images</code>.
     */
    public void setExtraImages(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>system.product.extra_images</code>.
     */
    public String getExtraImages() {
        return (String) get(3);
    }

    /**
     * Setter for <code>system.product.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>system.product.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>system.product.update_date</code>.
     */
    public void setUpdateDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>system.product.update_date</code>.
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>system.product.auth_code</code>.
     */
    public void setAuthCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>system.product.auth_code</code>.
     */
    public String getAuthCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>system.product.enable</code>.
     */
    public void setEnable(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>system.product.enable</code>.
     */
    public Boolean getEnable() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Timestamp, Timestamp, String, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Timestamp, Timestamp, String, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Product.PRODUCT.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Product.PRODUCT.SKU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Product.PRODUCT.IMAGE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Product.PRODUCT.EXTRA_IMAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Product.PRODUCT.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Product.PRODUCT.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Product.PRODUCT.AUTH_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Product.PRODUCT.ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSkuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getExtraImages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSkuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getExtraImages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(String value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(String value) {
        setSkuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(String value) {
        setImageUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(String value) {
        setExtraImages(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value7(String value) {
        setAuthCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value8(Boolean value) {
        setEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(String value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(String productId, String skuName, String imageUrl, String extraImages, Timestamp createDate, Timestamp updateDate, String authCode, Boolean enable) {
        super(Product.PRODUCT);

        set(0, productId);
        set(1, skuName);
        set(2, imageUrl);
        set(3, extraImages);
        set(4, createDate);
        set(5, updateDate);
        set(6, authCode);
        set(7, enable);
    }
}
