/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish_api;


import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import tanggod.github.io.config.database.repository.wish_api.tables.BatchBase;
import tanggod.github.io.config.database.repository.wish_api.tables.Campaigns;
import tanggod.github.io.config.database.repository.wish_api.tables.FinanceSyncOrderStatus;
import tanggod.github.io.config.database.repository.wish_api.tables.Order;
import tanggod.github.io.config.database.repository.wish_api.tables.Penalty;
import tanggod.github.io.config.database.repository.wish_api.tables.Product;
import tanggod.github.io.config.database.repository.wish_api.tables.Tracking;
import tanggod.github.io.config.database.repository.wish_api.tables.Variation;
import tanggod.github.io.config.database.repository.wish_api.tables.records.BatchBaseRecord;
import tanggod.github.io.config.database.repository.wish_api.tables.records.CampaignsRecord;
import tanggod.github.io.config.database.repository.wish_api.tables.records.FinanceSyncOrderStatusRecord;
import tanggod.github.io.config.database.repository.wish_api.tables.records.OrderRecord;
import tanggod.github.io.config.database.repository.wish_api.tables.records.PenaltyRecord;
import tanggod.github.io.config.database.repository.wish_api.tables.records.ProductRecord;
import tanggod.github.io.config.database.repository.wish_api.tables.records.TrackingRecord;
import tanggod.github.io.config.database.repository.wish_api.tables.records.VariationRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>wish_api</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BatchBaseRecord> KEY_BATCH_BASE_PRIMARY = UniqueKeys0.KEY_BATCH_BASE_PRIMARY;
    public static final UniqueKey<CampaignsRecord> KEY_CAMPAIGNS_PRIMARY = UniqueKeys0.KEY_CAMPAIGNS_PRIMARY;
    public static final UniqueKey<FinanceSyncOrderStatusRecord> KEY_FINANCE_SYNC_ORDER_STATUS_PRIMARY = UniqueKeys0.KEY_FINANCE_SYNC_ORDER_STATUS_PRIMARY;
    public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = UniqueKeys0.KEY_ORDER_PRIMARY;
    public static final UniqueKey<PenaltyRecord> KEY_PENALTY_PRIMARY = UniqueKeys0.KEY_PENALTY_PRIMARY;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<TrackingRecord> KEY_TRACKING_PRIMARY = UniqueKeys0.KEY_TRACKING_PRIMARY;
    public static final UniqueKey<VariationRecord> KEY_VARIATION_PRIMARY = UniqueKeys0.KEY_VARIATION_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<BatchBaseRecord> KEY_BATCH_BASE_PRIMARY = Internal.createUniqueKey(BatchBase.BATCH_BASE, "KEY_batch_base_PRIMARY", BatchBase.BATCH_BASE.BATCH_CODE);
        public static final UniqueKey<CampaignsRecord> KEY_CAMPAIGNS_PRIMARY = Internal.createUniqueKey(Campaigns.CAMPAIGNS, "KEY_campaigns_PRIMARY", Campaigns.CAMPAIGNS.ID);
        public static final UniqueKey<FinanceSyncOrderStatusRecord> KEY_FINANCE_SYNC_ORDER_STATUS_PRIMARY = Internal.createUniqueKey(FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS, "KEY_finance_sync_order_status_PRIMARY", FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.ID);
        public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = Internal.createUniqueKey(Order.ORDER, "KEY_order_PRIMARY", Order.ORDER.ID);
        public static final UniqueKey<PenaltyRecord> KEY_PENALTY_PRIMARY = Internal.createUniqueKey(Penalty.PENALTY, "KEY_penalty_PRIMARY", Penalty.PENALTY.ID);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, "KEY_product_PRIMARY", Product.PRODUCT.PRODUCT_ID);
        public static final UniqueKey<TrackingRecord> KEY_TRACKING_PRIMARY = Internal.createUniqueKey(Tracking.TRACKING, "KEY_tracking_PRIMARY", Tracking.TRACKING.PRID);
        public static final UniqueKey<VariationRecord> KEY_VARIATION_PRIMARY = Internal.createUniqueKey(Variation.VARIATION, "KEY_variation_PRIMARY", Variation.VARIATION.VARIATION_ID);
    }
}
