/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.system;


import javax.annotation.Generated;

import tanggod.github.io.config.database.repository.system.tables.Binding;
import tanggod.github.io.config.database.repository.system.tables.Product;
import tanggod.github.io.config.database.repository.system.tables.Variation;


/**
 * Convenience access to all tables in system
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>system.binding</code>.
     */
    public static final Binding BINDING = tanggod.github.io.config.database.repository.system.tables.Binding.BINDING;

    /**
     * The table <code>system.product</code>.
     */
    public static final Product PRODUCT = tanggod.github.io.config.database.repository.system.tables.Product.PRODUCT;

    /**
     * The table <code>system.variation</code>.
     */
    public static final Variation VARIATION = tanggod.github.io.config.database.repository.system.tables.Variation.VARIATION;
}
