/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.dummy_data;


import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import tanggod.github.io.config.database.repository.dummy_data.tables.DummyAutucode;
import tanggod.github.io.config.database.repository.dummy_data.tables.DummyChatgptUserName;
import tanggod.github.io.config.database.repository.dummy_data.tables.DummyConfig;
import tanggod.github.io.config.database.repository.dummy_data.tables.DummyOrder;
import tanggod.github.io.config.database.repository.dummy_data.tables.DummyProduct;
import tanggod.github.io.config.database.repository.dummy_data.tables.DummyUserInfo;
import tanggod.github.io.config.database.repository.dummy_data.tables.records.DummyAutucodeRecord;
import tanggod.github.io.config.database.repository.dummy_data.tables.records.DummyChatgptUserNameRecord;
import tanggod.github.io.config.database.repository.dummy_data.tables.records.DummyConfigRecord;
import tanggod.github.io.config.database.repository.dummy_data.tables.records.DummyOrderRecord;
import tanggod.github.io.config.database.repository.dummy_data.tables.records.DummyProductRecord;
import tanggod.github.io.config.database.repository.dummy_data.tables.records.DummyUserInfoRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>dummy_data</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DummyAutucodeRecord> KEY_DUMMY_AUTUCODE_PRIMARY = UniqueKeys0.KEY_DUMMY_AUTUCODE_PRIMARY;
    public static final UniqueKey<DummyChatgptUserNameRecord> KEY_DUMMY_CHATGPT_USER_NAME_PRIMARY = UniqueKeys0.KEY_DUMMY_CHATGPT_USER_NAME_PRIMARY;
    public static final UniqueKey<DummyConfigRecord> KEY_DUMMY_CONFIG_PRIMARY = UniqueKeys0.KEY_DUMMY_CONFIG_PRIMARY;
    public static final UniqueKey<DummyOrderRecord> KEY_DUMMY_ORDER_PRIMARY = UniqueKeys0.KEY_DUMMY_ORDER_PRIMARY;
    public static final UniqueKey<DummyProductRecord> KEY_DUMMY_PRODUCT_PRIMARY = UniqueKeys0.KEY_DUMMY_PRODUCT_PRIMARY;
    public static final UniqueKey<DummyUserInfoRecord> KEY_DUMMY_USER_INFO_PRIMARY = UniqueKeys0.KEY_DUMMY_USER_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<DummyAutucodeRecord> KEY_DUMMY_AUTUCODE_PRIMARY = Internal.createUniqueKey(DummyAutucode.DUMMY_AUTUCODE, "KEY_dummy_autuCode_PRIMARY", DummyAutucode.DUMMY_AUTUCODE.ID);
        public static final UniqueKey<DummyChatgptUserNameRecord> KEY_DUMMY_CHATGPT_USER_NAME_PRIMARY = Internal.createUniqueKey(DummyChatgptUserName.DUMMY_CHATGPT_USER_NAME, "KEY_dummy_chatgpt_user_name_PRIMARY", DummyChatgptUserName.DUMMY_CHATGPT_USER_NAME.ID);
        public static final UniqueKey<DummyConfigRecord> KEY_DUMMY_CONFIG_PRIMARY = Internal.createUniqueKey(DummyConfig.DUMMY_CONFIG, "KEY_dummy_config_PRIMARY", DummyConfig.DUMMY_CONFIG.ID);
        public static final UniqueKey<DummyOrderRecord> KEY_DUMMY_ORDER_PRIMARY = Internal.createUniqueKey(DummyOrder.DUMMY_ORDER, "KEY_dummy_order_PRIMARY", DummyOrder.DUMMY_ORDER.ID);
        public static final UniqueKey<DummyProductRecord> KEY_DUMMY_PRODUCT_PRIMARY = Internal.createUniqueKey(DummyProduct.DUMMY_PRODUCT, "KEY_dummy_product_PRIMARY", DummyProduct.DUMMY_PRODUCT.ID);
        public static final UniqueKey<DummyUserInfoRecord> KEY_DUMMY_USER_INFO_PRIMARY = Internal.createUniqueKey(DummyUserInfo.DUMMY_USER_INFO, "KEY_dummy_user_info_PRIMARY", DummyUserInfo.DUMMY_USER_INFO.ID);
    }
}
