/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import tanggod.github.io.config.database.repository.wish.tables.Announcement;
import tanggod.github.io.config.database.repository.wish.tables.CategoryData;
import tanggod.github.io.config.database.repository.wish.tables.CategoryDataDataAnalysis;
import tanggod.github.io.config.database.repository.wish.tables.CategoryDataDataAnalysisSync;
import tanggod.github.io.config.database.repository.wish.tables.CategoryDataPermission;
import tanggod.github.io.config.database.repository.wish.tables.CategoryDataRequestCode;
import tanggod.github.io.config.database.repository.wish.tables.CollectionDataFilter;
import tanggod.github.io.config.database.repository.wish.tables.CollectionDataParameter;
import tanggod.github.io.config.database.repository.wish.tables.CollectionDataUser;
import tanggod.github.io.config.database.repository.wish.tables.CostPbCost;
import tanggod.github.io.config.database.repository.wish.tables.CostPbDianxiaomi;
import tanggod.github.io.config.database.repository.wish.tables.CostTotal;
import tanggod.github.io.config.database.repository.wish.tables.Customizeinfo;
import tanggod.github.io.config.database.repository.wish.tables.Customizeproduct;
import tanggod.github.io.config.database.repository.wish.tables.DesktopApplication;
import tanggod.github.io.config.database.repository.wish.tables.JieZiManCookie;
import tanggod.github.io.config.database.repository.wish.tables.JzmPurchaseOrder;
import tanggod.github.io.config.database.repository.wish.tables.JzmWarehouseOrderCode;
import tanggod.github.io.config.database.repository.wish.tables.JzmWishUser;
import tanggod.github.io.config.database.repository.wish.tables.OperationHistory;
import tanggod.github.io.config.database.repository.wish.tables.PbProduct;
import tanggod.github.io.config.database.repository.wish.tables.ProductBoostTemplateProduct;
import tanggod.github.io.config.database.repository.wish.tables.ProductBoostTemplateRecord;
import tanggod.github.io.config.database.repository.wish.tables.ProductBoostTemplateUser;
import tanggod.github.io.config.database.repository.wish.tables.ProductInventoryAddRecord;
import tanggod.github.io.config.database.repository.wish.tables.ProductPriceTrackingTemplate;
import tanggod.github.io.config.database.repository.wish.tables.ProductSalesMonitor;
import tanggod.github.io.config.database.repository.wish.tables.Productinfo;
import tanggod.github.io.config.database.repository.wish.tables.SkuFile;
import tanggod.github.io.config.database.repository.wish.tables.SkuImage;
import tanggod.github.io.config.database.repository.wish.tables.SmsRecord;
import tanggod.github.io.config.database.repository.wish.tables.SmsVerificationCode;
import tanggod.github.io.config.database.repository.wish.tables.Taskrecord;
import tanggod.github.io.config.database.repository.wish.tables.TiktokOrder;
import tanggod.github.io.config.database.repository.wish.tables.User;
import tanggod.github.io.config.database.repository.wish.tables.WebsiteAddress;
import tanggod.github.io.config.database.repository.wish.tables.WebsiteTask;
import tanggod.github.io.config.database.repository.wish.tables.WishAuth;
import tanggod.github.io.config.database.repository.wish.tables.WishCategory;
import tanggod.github.io.config.database.repository.wish.tables.WishCvsRecord;
import tanggod.github.io.config.database.repository.wish.tables.WishKeywordSearch;
import tanggod.github.io.config.database.repository.wish.tables.WishProduct;
import tanggod.github.io.config.database.repository.wish.tables.WishProductBoostDetail;
import tanggod.github.io.config.database.repository.wish.tables.WishProductNumberSold;
import tanggod.github.io.config.database.repository.wish.tables.WishProductSalesMonitorData;
import tanggod.github.io.config.database.repository.wish.tables.WishProductSalesMonitorUser;
import tanggod.github.io.config.database.repository.wish.tables.WishSoldDate;
import tanggod.github.io.config.database.repository.wish.tables.WishStockAutomation;
import tanggod.github.io.config.database.repository.wish.tables.WishUser;
import tanggod.github.io.config.database.repository.wish.tables.WishVariant;
import tanggod.github.io.config.database.repository.wish.tables.WishWebCookie;


/**
 * A class modelling indexes of tables of the <code>wish</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ANNOUNCEMENT_PRIMARY = Indexes0.ANNOUNCEMENT_PRIMARY;
    public static final Index CATEGORY_DATA_$_CATEGORY_ID = Indexes0.CATEGORY_DATA_$_CATEGORY_ID;
    public static final Index CATEGORY_DATA_$_CREATEDATE = Indexes0.CATEGORY_DATA_$_CREATEDATE;
    public static final Index CATEGORY_DATA_$_MAIJIAWANG_GENTIME = Indexes0.CATEGORY_DATA_$_MAIJIAWANG_GENTIME;
    public static final Index CATEGORY_DATA_$_PRODUCTID = Indexes0.CATEGORY_DATA_$_PRODUCTID;
    public static final Index CATEGORY_DATA_$_SEARCH = Indexes0.CATEGORY_DATA_$_SEARCH;
    public static final Index CATEGORY_DATA_$_STATE = Indexes0.CATEGORY_DATA_$_STATE;
    public static final Index CATEGORY_DATA_PRIMARY = Indexes0.CATEGORY_DATA_PRIMARY;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS__60ADDED_TIME_60 = Indexes0.CATEGORY_DATA_DATA_ANALYSIS__60ADDED_TIME_60;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS__60CATEGORY_DATA_ID_60 = Indexes0.CATEGORY_DATA_DATA_ANALYSIS__60CATEGORY_DATA_ID_60;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS__60MAXIMUMSALES_60 = Indexes0.CATEGORY_DATA_DATA_ANALYSIS__60MAXIMUMSALES_60;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS__60REQUEST_CODE_60 = Indexes0.CATEGORY_DATA_DATA_ANALYSIS__60REQUEST_CODE_60;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS__60SYNC_CODE_60 = Indexes0.CATEGORY_DATA_DATA_ANALYSIS__60SYNC_CODE_60;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS__60SYSTEM_DELETE_60 = Indexes0.CATEGORY_DATA_DATA_ANALYSIS__60SYSTEM_DELETE_60;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS__60WISH_CATEGORY_ID_60 = Indexes0.CATEGORY_DATA_DATA_ANALYSIS__60WISH_CATEGORY_ID_60;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS_PRIMARY = Indexes0.CATEGORY_DATA_DATA_ANALYSIS_PRIMARY;
    public static final Index CATEGORY_DATA_DATA_ANALYSIS_SYNC_PRIMARY = Indexes0.CATEGORY_DATA_DATA_ANALYSIS_SYNC_PRIMARY;
    public static final Index CATEGORY_DATA_PERMISSION_PRIMARY = Indexes0.CATEGORY_DATA_PERMISSION_PRIMARY;
    public static final Index CATEGORY_DATA_REQUEST_CODE_PRIMARY = Indexes0.CATEGORY_DATA_REQUEST_CODE_PRIMARY;
    public static final Index COLLECTION_DATA_FILTER_PRIMARY = Indexes0.COLLECTION_DATA_FILTER_PRIMARY;
    public static final Index COLLECTION_DATA_FILTER_PRODUCTID = Indexes0.COLLECTION_DATA_FILTER_PRODUCTID;
    public static final Index COLLECTION_DATA_FILTER_REATE_DATA = Indexes0.COLLECTION_DATA_FILTER_REATE_DATA;
    public static final Index COLLECTION_DATA_PARAMETER_$1 = Indexes0.COLLECTION_DATA_PARAMETER_$1;
    public static final Index COLLECTION_DATA_PARAMETER_$2 = Indexes0.COLLECTION_DATA_PARAMETER_$2;
    public static final Index COLLECTION_DATA_PARAMETER_PRIMARY = Indexes0.COLLECTION_DATA_PARAMETER_PRIMARY;
    public static final Index COLLECTION_DATA_USER_PRIMARY = Indexes0.COLLECTION_DATA_USER_PRIMARY;
    public static final Index COST_PB_COST_PRIMARY = Indexes0.COST_PB_COST_PRIMARY;
    public static final Index COST_PB_DIANXIAOMI_PRIMARY = Indexes0.COST_PB_DIANXIAOMI_PRIMARY;
    public static final Index COST_TOTAL_PRIMARY = Indexes0.COST_TOTAL_PRIMARY;
    public static final Index CUSTOMIZEINFO_PRIMARY = Indexes0.CUSTOMIZEINFO_PRIMARY;
    public static final Index CUSTOMIZEPRODUCT_PRIMARY = Indexes0.CUSTOMIZEPRODUCT_PRIMARY;
    public static final Index DESKTOP_APPLICATION_PRIMARY = Indexes0.DESKTOP_APPLICATION_PRIMARY;
    public static final Index JIE_ZI_MAN_COOKIE_PRIMARY = Indexes0.JIE_ZI_MAN_COOKIE_PRIMARY;
    public static final Index JZM_PURCHASE_ORDER_PRIMARY = Indexes0.JZM_PURCHASE_ORDER_PRIMARY;
    public static final Index JZM_WAREHOUSE_ORDER_CODE_PRIMARY = Indexes0.JZM_WAREHOUSE_ORDER_CODE_PRIMARY;
    public static final Index JZM_WISH_USER_PRIMARY = Indexes0.JZM_WISH_USER_PRIMARY;
    public static final Index OPERATION_HISTORY_PRIMARY = Indexes0.OPERATION_HISTORY_PRIMARY;
    public static final Index PB_PRODUCT_PRIMARY = Indexes0.PB_PRODUCT_PRIMARY;
    public static final Index PRODUCTINFO_$_PRODUCTID = Indexes0.PRODUCTINFO_$_PRODUCTID;
    public static final Index PRODUCTINFO_PRIMARY = Indexes0.PRODUCTINFO_PRIMARY;
    public static final Index PRODUCT_BOOST_TEMPLATE_PRODUCT_PRIMARY = Indexes0.PRODUCT_BOOST_TEMPLATE_PRODUCT_PRIMARY;
    public static final Index PRODUCT_BOOST_TEMPLATE_RECORD_1 = Indexes0.PRODUCT_BOOST_TEMPLATE_RECORD_1;
    public static final Index PRODUCT_BOOST_TEMPLATE_RECORD_2 = Indexes0.PRODUCT_BOOST_TEMPLATE_RECORD_2;
    public static final Index PRODUCT_BOOST_TEMPLATE_RECORD_3 = Indexes0.PRODUCT_BOOST_TEMPLATE_RECORD_3;
    public static final Index PRODUCT_BOOST_TEMPLATE_RECORD_4 = Indexes0.PRODUCT_BOOST_TEMPLATE_RECORD_4;
    public static final Index PRODUCT_BOOST_TEMPLATE_RECORD_PRIMARY = Indexes0.PRODUCT_BOOST_TEMPLATE_RECORD_PRIMARY;
    public static final Index PRODUCT_BOOST_TEMPLATE_USER_PRIMARY = Indexes0.PRODUCT_BOOST_TEMPLATE_USER_PRIMARY;
    public static final Index PRODUCT_INVENTORY_ADD_RECORD_PRIMARY = Indexes0.PRODUCT_INVENTORY_ADD_RECORD_PRIMARY;
    public static final Index PRODUCT_PRICE_TRACKING_TEMPLATE__60VARIATION_ID_60 = Indexes0.PRODUCT_PRICE_TRACKING_TEMPLATE__60VARIATION_ID_60;
    public static final Index PRODUCT_PRICE_TRACKING_TEMPLATE_PRIMARY = Indexes0.PRODUCT_PRICE_TRACKING_TEMPLATE_PRIMARY;
    public static final Index PRODUCT_SALES_MONITOR_PRIMARY = Indexes0.PRODUCT_SALES_MONITOR_PRIMARY;
    public static final Index SKU_FILE_PRIMARY = Indexes0.SKU_FILE_PRIMARY;
    public static final Index SKU_IMAGE_PRIMARY = Indexes0.SKU_IMAGE_PRIMARY;
    public static final Index SMS_RECORD_PRIMARY = Indexes0.SMS_RECORD_PRIMARY;
    public static final Index SMS_VERIFICATION_CODE_PRIMARY = Indexes0.SMS_VERIFICATION_CODE_PRIMARY;
    public static final Index TASKRECORD_PRIMARY = Indexes0.TASKRECORD_PRIMARY;
    public static final Index TIKTOK_ORDER_1 = Indexes0.TIKTOK_ORDER_1;
    public static final Index TIKTOK_ORDER_2 = Indexes0.TIKTOK_ORDER_2;
    public static final Index TIKTOK_ORDER_PRIMARY = Indexes0.TIKTOK_ORDER_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index WEBSITE_ADDRESS_PRIMARY = Indexes0.WEBSITE_ADDRESS_PRIMARY;
    public static final Index WEBSITE_TASK_PRIMARY = Indexes0.WEBSITE_TASK_PRIMARY;
    public static final Index WISH_AUTH_PRIMARY = Indexes0.WISH_AUTH_PRIMARY;
    public static final Index WISH_CATEGORY_PRIMARY = Indexes0.WISH_CATEGORY_PRIMARY;
    public static final Index WISH_CVS_RECORD_PRIMARY = Indexes0.WISH_CVS_RECORD_PRIMARY;
    public static final Index WISH_KEYWORD_SEARCH_PRIMARY = Indexes0.WISH_KEYWORD_SEARCH_PRIMARY;
    public static final Index WISH_PRODUCT_1 = Indexes0.WISH_PRODUCT_1;
    public static final Index WISH_PRODUCT_DATE_UPLOADED = Indexes0.WISH_PRODUCT_DATE_UPLOADED;
    public static final Index WISH_PRODUCT_ID = Indexes0.WISH_PRODUCT_ID;
    public static final Index WISH_PRODUCT_PRIMARY = Indexes0.WISH_PRODUCT_PRIMARY;
    public static final Index WISH_PRODUCT_BOOST_DETAIL_PRIMARY = Indexes0.WISH_PRODUCT_BOOST_DETAIL_PRIMARY;
    public static final Index WISH_PRODUCT_NUMBER_SOLD_PRIMARY = Indexes0.WISH_PRODUCT_NUMBER_SOLD_PRIMARY;
    public static final Index WISH_PRODUCT_NUMBER_SOLD_PRODUCT_ID = Indexes0.WISH_PRODUCT_NUMBER_SOLD_PRODUCT_ID;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_AUTH_CODE = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_AUTH_CODE;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_CREATE_DATE = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_CREATE_DATE;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_DATE_UPLOADED = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_DATE_UPLOADED;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_INVENTORY_STATUS = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_INVENTORY_STATUS;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_PARENT_SKU = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_PARENT_SKU;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_PRIMARY = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_PRIMARY;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_PRODUCT_ID = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_PRODUCT_ID;
    public static final Index WISH_PRODUCT_SALES_MONITOR_DATA_VARIANT_SKU = Indexes0.WISH_PRODUCT_SALES_MONITOR_DATA_VARIANT_SKU;
    public static final Index WISH_PRODUCT_SALES_MONITOR_USER_AUTH_CODE = Indexes0.WISH_PRODUCT_SALES_MONITOR_USER_AUTH_CODE;
    public static final Index WISH_PRODUCT_SALES_MONITOR_USER_FILTER_STATUS = Indexes0.WISH_PRODUCT_SALES_MONITOR_USER_FILTER_STATUS;
    public static final Index WISH_PRODUCT_SALES_MONITOR_USER_PRIMARY = Indexes0.WISH_PRODUCT_SALES_MONITOR_USER_PRIMARY;
    public static final Index WISH_PRODUCT_SALES_MONITOR_USER_SORT = Indexes0.WISH_PRODUCT_SALES_MONITOR_USER_SORT;
    public static final Index WISH_SOLD_DATE_PRIMARY = Indexes0.WISH_SOLD_DATE_PRIMARY;
    public static final Index WISH_STOCK_AUTOMATION_1 = Indexes0.WISH_STOCK_AUTOMATION_1;
    public static final Index WISH_STOCK_AUTOMATION_2 = Indexes0.WISH_STOCK_AUTOMATION_2;
    public static final Index WISH_STOCK_AUTOMATION_3 = Indexes0.WISH_STOCK_AUTOMATION_3;
    public static final Index WISH_STOCK_AUTOMATION_4 = Indexes0.WISH_STOCK_AUTOMATION_4;
    public static final Index WISH_STOCK_AUTOMATION_5 = Indexes0.WISH_STOCK_AUTOMATION_5;
    public static final Index WISH_STOCK_AUTOMATION_6 = Indexes0.WISH_STOCK_AUTOMATION_6;
    public static final Index WISH_STOCK_AUTOMATION_PRIMARY = Indexes0.WISH_STOCK_AUTOMATION_PRIMARY;
    public static final Index WISH_USER_PRIMARY = Indexes0.WISH_USER_PRIMARY;
    public static final Index WISH_VARIANT_PRIMARY = Indexes0.WISH_VARIANT_PRIMARY;
    public static final Index WISH_VARIANT_PRODUCT_ID = Indexes0.WISH_VARIANT_PRODUCT_ID;
    public static final Index WISH_WEB_COOKIE_PRIMARY = Indexes0.WISH_WEB_COOKIE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ANNOUNCEMENT_PRIMARY = Internal.createIndex("PRIMARY", Announcement.ANNOUNCEMENT, new OrderField[] { Announcement.ANNOUNCEMENT.ID }, true);
        public static Index CATEGORY_DATA_$_CATEGORY_ID = Internal.createIndex("$_category_id", CategoryData.CATEGORY_DATA, new OrderField[] { CategoryData.CATEGORY_DATA.CATEGORY_ID }, false);
        public static Index CATEGORY_DATA_$_CREATEDATE = Internal.createIndex("$_createDate", CategoryData.CATEGORY_DATA, new OrderField[] { CategoryData.CATEGORY_DATA.CREATEDATE }, false);
        public static Index CATEGORY_DATA_$_MAIJIAWANG_GENTIME = Internal.createIndex("$_maijiawang_genTime", CategoryData.CATEGORY_DATA, new OrderField[] { CategoryData.CATEGORY_DATA.MAIJIAWANG_GENTIME }, false);
        public static Index CATEGORY_DATA_$_PRODUCTID = Internal.createIndex("$_productId", CategoryData.CATEGORY_DATA, new OrderField[] { CategoryData.CATEGORY_DATA.PRODUCTID }, false);
        public static Index CATEGORY_DATA_$_SEARCH = Internal.createIndex("$_search", CategoryData.CATEGORY_DATA, new OrderField[] { CategoryData.CATEGORY_DATA.SEARCH }, false);
        public static Index CATEGORY_DATA_$_STATE = Internal.createIndex("$_state", CategoryData.CATEGORY_DATA, new OrderField[] { CategoryData.CATEGORY_DATA.STATE }, false);
        public static Index CATEGORY_DATA_PRIMARY = Internal.createIndex("PRIMARY", CategoryData.CATEGORY_DATA, new OrderField[] { CategoryData.CATEGORY_DATA.ID }, true);
        public static Index CATEGORY_DATA_DATA_ANALYSIS__60ADDED_TIME_60 = Internal.createIndex("`added_time`", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.ADDED_TIME }, false);
        public static Index CATEGORY_DATA_DATA_ANALYSIS__60CATEGORY_DATA_ID_60 = Internal.createIndex("`category_data_id`", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.CATEGORY_DATA_ID }, false);
        public static Index CATEGORY_DATA_DATA_ANALYSIS__60MAXIMUMSALES_60 = Internal.createIndex("`maximumSales`", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.MAXIMUMSALES }, false);
        public static Index CATEGORY_DATA_DATA_ANALYSIS__60REQUEST_CODE_60 = Internal.createIndex("`request_code`", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.REQUEST_CODE }, false);
        public static Index CATEGORY_DATA_DATA_ANALYSIS__60SYNC_CODE_60 = Internal.createIndex("`sync_code`", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.SYNC_CODE }, false);
        public static Index CATEGORY_DATA_DATA_ANALYSIS__60SYSTEM_DELETE_60 = Internal.createIndex("`system_delete`", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.SYSTEM_DELETE }, false);
        public static Index CATEGORY_DATA_DATA_ANALYSIS__60WISH_CATEGORY_ID_60 = Internal.createIndex("`wish_category_id`", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.WISH_CATEGORY_ID }, false);
        public static Index CATEGORY_DATA_DATA_ANALYSIS_PRIMARY = Internal.createIndex("PRIMARY", CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS, new OrderField[] { CategoryDataDataAnalysis.CATEGORY_DATA_DATA_ANALYSIS.ID }, true);
        public static Index CATEGORY_DATA_DATA_ANALYSIS_SYNC_PRIMARY = Internal.createIndex("PRIMARY", CategoryDataDataAnalysisSync.CATEGORY_DATA_DATA_ANALYSIS_SYNC, new OrderField[] { CategoryDataDataAnalysisSync.CATEGORY_DATA_DATA_ANALYSIS_SYNC.ID }, true);
        public static Index CATEGORY_DATA_PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", CategoryDataPermission.CATEGORY_DATA_PERMISSION, new OrderField[] { CategoryDataPermission.CATEGORY_DATA_PERMISSION.ID }, true);
        public static Index CATEGORY_DATA_REQUEST_CODE_PRIMARY = Internal.createIndex("PRIMARY", CategoryDataRequestCode.CATEGORY_DATA_REQUEST_CODE, new OrderField[] { CategoryDataRequestCode.CATEGORY_DATA_REQUEST_CODE.ID }, true);
        public static Index COLLECTION_DATA_FILTER_PRIMARY = Internal.createIndex("PRIMARY", CollectionDataFilter.COLLECTION_DATA_FILTER, new OrderField[] { CollectionDataFilter.COLLECTION_DATA_FILTER.ID }, true);
        public static Index COLLECTION_DATA_FILTER_PRODUCTID = Internal.createIndex("productId", CollectionDataFilter.COLLECTION_DATA_FILTER, new OrderField[] { CollectionDataFilter.COLLECTION_DATA_FILTER.PRODUCTID }, false);
        public static Index COLLECTION_DATA_FILTER_REATE_DATA = Internal.createIndex("reate_data", CollectionDataFilter.COLLECTION_DATA_FILTER, new OrderField[] { CollectionDataFilter.COLLECTION_DATA_FILTER.CREATE_DATE }, false);
        public static Index COLLECTION_DATA_PARAMETER_$1 = Internal.createIndex("$1", CollectionDataParameter.COLLECTION_DATA_PARAMETER, new OrderField[] { CollectionDataParameter.COLLECTION_DATA_PARAMETER.PRODUCTID }, false);
        public static Index COLLECTION_DATA_PARAMETER_$2 = Internal.createIndex("$2", CollectionDataParameter.COLLECTION_DATA_PARAMETER, new OrderField[] { CollectionDataParameter.COLLECTION_DATA_PARAMETER.COLLECTION_DATA_USER_ID }, false);
        public static Index COLLECTION_DATA_PARAMETER_PRIMARY = Internal.createIndex("PRIMARY", CollectionDataParameter.COLLECTION_DATA_PARAMETER, new OrderField[] { CollectionDataParameter.COLLECTION_DATA_PARAMETER.ID }, true);
        public static Index COLLECTION_DATA_USER_PRIMARY = Internal.createIndex("PRIMARY", CollectionDataUser.COLLECTION_DATA_USER, new OrderField[] { CollectionDataUser.COLLECTION_DATA_USER.ID }, true);
        public static Index COST_PB_COST_PRIMARY = Internal.createIndex("PRIMARY", CostPbCost.COST_PB_COST, new OrderField[] { CostPbCost.COST_PB_COST.ID }, true);
        public static Index COST_PB_DIANXIAOMI_PRIMARY = Internal.createIndex("PRIMARY", CostPbDianxiaomi.COST_PB_DIANXIAOMI, new OrderField[] { CostPbDianxiaomi.COST_PB_DIANXIAOMI.ID }, true);
        public static Index COST_TOTAL_PRIMARY = Internal.createIndex("PRIMARY", CostTotal.COST_TOTAL, new OrderField[] { CostTotal.COST_TOTAL.ID }, true);
        public static Index CUSTOMIZEINFO_PRIMARY = Internal.createIndex("PRIMARY", Customizeinfo.CUSTOMIZEINFO, new OrderField[] { Customizeinfo.CUSTOMIZEINFO.ID }, true);
        public static Index CUSTOMIZEPRODUCT_PRIMARY = Internal.createIndex("PRIMARY", Customizeproduct.CUSTOMIZEPRODUCT, new OrderField[] { Customizeproduct.CUSTOMIZEPRODUCT.ID }, true);
        public static Index DESKTOP_APPLICATION_PRIMARY = Internal.createIndex("PRIMARY", DesktopApplication.DESKTOP_APPLICATION, new OrderField[] { DesktopApplication.DESKTOP_APPLICATION.ID }, true);
        public static Index JIE_ZI_MAN_COOKIE_PRIMARY = Internal.createIndex("PRIMARY", JieZiManCookie.JIE_ZI_MAN_COOKIE, new OrderField[] { JieZiManCookie.JIE_ZI_MAN_COOKIE.ID }, true);
        public static Index JZM_PURCHASE_ORDER_PRIMARY = Internal.createIndex("PRIMARY", JzmPurchaseOrder.JZM_PURCHASE_ORDER, new OrderField[] { JzmPurchaseOrder.JZM_PURCHASE_ORDER.ID }, true);
        public static Index JZM_WAREHOUSE_ORDER_CODE_PRIMARY = Internal.createIndex("PRIMARY", JzmWarehouseOrderCode.JZM_WAREHOUSE_ORDER_CODE, new OrderField[] { JzmWarehouseOrderCode.JZM_WAREHOUSE_ORDER_CODE.WAREHOUSE_ORDER_CODE }, true);
        public static Index JZM_WISH_USER_PRIMARY = Internal.createIndex("PRIMARY", JzmWishUser.JZM_WISH_USER, new OrderField[] { JzmWishUser.JZM_WISH_USER.ID }, true);
        public static Index OPERATION_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", OperationHistory.OPERATION_HISTORY, new OrderField[] { OperationHistory.OPERATION_HISTORY.ID }, true);
        public static Index PB_PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", PbProduct.PB_PRODUCT, new OrderField[] { PbProduct.PB_PRODUCT.ID }, true);
        public static Index PRODUCTINFO_$_PRODUCTID = Internal.createIndex("$_productId", Productinfo.PRODUCTINFO, new OrderField[] { Productinfo.PRODUCTINFO.PRODUCTID }, false);
        public static Index PRODUCTINFO_PRIMARY = Internal.createIndex("PRIMARY", Productinfo.PRODUCTINFO, new OrderField[] { Productinfo.PRODUCTINFO.ID }, true);
        public static Index PRODUCT_BOOST_TEMPLATE_PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", ProductBoostTemplateProduct.PRODUCT_BOOST_TEMPLATE_PRODUCT, new OrderField[] { ProductBoostTemplateProduct.PRODUCT_BOOST_TEMPLATE_PRODUCT.ID }, true);
        public static Index PRODUCT_BOOST_TEMPLATE_RECORD_1 = Internal.createIndex("1", ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD, new OrderField[] { ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD.CREATE_DATE }, false);
        public static Index PRODUCT_BOOST_TEMPLATE_RECORD_2 = Internal.createIndex("2", ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD, new OrderField[] { ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD.AUTH_CODE }, false);
        public static Index PRODUCT_BOOST_TEMPLATE_RECORD_3 = Internal.createIndex("3", ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD, new OrderField[] { ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD.PRODUCT_ID }, false);
        public static Index PRODUCT_BOOST_TEMPLATE_RECORD_4 = Internal.createIndex("4", ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD, new OrderField[] { ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD.CAMPAIGN_ID }, false);
        public static Index PRODUCT_BOOST_TEMPLATE_RECORD_PRIMARY = Internal.createIndex("PRIMARY", ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD, new OrderField[] { ProductBoostTemplateRecord.PRODUCT_BOOST_TEMPLATE_RECORD.ID }, true);
        public static Index PRODUCT_BOOST_TEMPLATE_USER_PRIMARY = Internal.createIndex("PRIMARY", ProductBoostTemplateUser.PRODUCT_BOOST_TEMPLATE_USER, new OrderField[] { ProductBoostTemplateUser.PRODUCT_BOOST_TEMPLATE_USER.AUTH_CODE }, true);
        public static Index PRODUCT_INVENTORY_ADD_RECORD_PRIMARY = Internal.createIndex("PRIMARY", ProductInventoryAddRecord.PRODUCT_INVENTORY_ADD_RECORD, new OrderField[] { ProductInventoryAddRecord.PRODUCT_INVENTORY_ADD_RECORD.ID, ProductInventoryAddRecord.PRODUCT_INVENTORY_ADD_RECORD.CREATE_DATE }, true);
        public static Index PRODUCT_PRICE_TRACKING_TEMPLATE__60VARIATION_ID_60 = Internal.createIndex("`variation_id`", ProductPriceTrackingTemplate.PRODUCT_PRICE_TRACKING_TEMPLATE, new OrderField[] { ProductPriceTrackingTemplate.PRODUCT_PRICE_TRACKING_TEMPLATE.VARIATION_ID }, false);
        public static Index PRODUCT_PRICE_TRACKING_TEMPLATE_PRIMARY = Internal.createIndex("PRIMARY", ProductPriceTrackingTemplate.PRODUCT_PRICE_TRACKING_TEMPLATE, new OrderField[] { ProductPriceTrackingTemplate.PRODUCT_PRICE_TRACKING_TEMPLATE.VARIATION_ID }, true);
        public static Index PRODUCT_SALES_MONITOR_PRIMARY = Internal.createIndex("PRIMARY", ProductSalesMonitor.PRODUCT_SALES_MONITOR, new OrderField[] { ProductSalesMonitor.PRODUCT_SALES_MONITOR.ID }, true);
        public static Index SKU_FILE_PRIMARY = Internal.createIndex("PRIMARY", SkuFile.SKU_FILE, new OrderField[] { SkuFile.SKU_FILE.ID }, true);
        public static Index SKU_IMAGE_PRIMARY = Internal.createIndex("PRIMARY", SkuImage.SKU_IMAGE, new OrderField[] { SkuImage.SKU_IMAGE.ID }, true);
        public static Index SMS_RECORD_PRIMARY = Internal.createIndex("PRIMARY", SmsRecord.SMS_RECORD, new OrderField[] { SmsRecord.SMS_RECORD.ID }, true);
        public static Index SMS_VERIFICATION_CODE_PRIMARY = Internal.createIndex("PRIMARY", SmsVerificationCode.SMS_VERIFICATION_CODE, new OrderField[] { SmsVerificationCode.SMS_VERIFICATION_CODE.ID }, true);
        public static Index TASKRECORD_PRIMARY = Internal.createIndex("PRIMARY", Taskrecord.TASKRECORD, new OrderField[] { Taskrecord.TASKRECORD.ID }, true);
        public static Index TIKTOK_ORDER_1 = Internal.createIndex("1", TiktokOrder.TIKTOK_ORDER, new OrderField[] { TiktokOrder.TIKTOK_ORDER.SYNC }, false);
        public static Index TIKTOK_ORDER_2 = Internal.createIndex("2", TiktokOrder.TIKTOK_ORDER, new OrderField[] { TiktokOrder.TIKTOK_ORDER.ORDER_ID }, false);
        public static Index TIKTOK_ORDER_PRIMARY = Internal.createIndex("PRIMARY", TiktokOrder.TIKTOK_ORDER, new OrderField[] { TiktokOrder.TIKTOK_ORDER.ORDER_ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index WEBSITE_ADDRESS_PRIMARY = Internal.createIndex("PRIMARY", WebsiteAddress.WEBSITE_ADDRESS, new OrderField[] { WebsiteAddress.WEBSITE_ADDRESS.ID }, true);
        public static Index WEBSITE_TASK_PRIMARY = Internal.createIndex("PRIMARY", WebsiteTask.WEBSITE_TASK, new OrderField[] { WebsiteTask.WEBSITE_TASK.ID }, true);
        public static Index WISH_AUTH_PRIMARY = Internal.createIndex("PRIMARY", WishAuth.WISH_AUTH, new OrderField[] { WishAuth.WISH_AUTH.ID }, true);
        public static Index WISH_CATEGORY_PRIMARY = Internal.createIndex("PRIMARY", WishCategory.WISH_CATEGORY, new OrderField[] { WishCategory.WISH_CATEGORY.ID }, true);
        public static Index WISH_CVS_RECORD_PRIMARY = Internal.createIndex("PRIMARY", WishCvsRecord.WISH_CVS_RECORD, new OrderField[] { WishCvsRecord.WISH_CVS_RECORD.JOB_ID }, true);
        public static Index WISH_KEYWORD_SEARCH_PRIMARY = Internal.createIndex("PRIMARY", WishKeywordSearch.WISH_KEYWORD_SEARCH, new OrderField[] { WishKeywordSearch.WISH_KEYWORD_SEARCH.ID }, true);
        public static Index WISH_PRODUCT_1 = Internal.createIndex("1", WishProduct.WISH_PRODUCT, new OrderField[] { WishProduct.WISH_PRODUCT.CREATE_DATE }, false);
        public static Index WISH_PRODUCT_DATE_UPLOADED = Internal.createIndex("date_uploaded", WishProduct.WISH_PRODUCT, new OrderField[] { WishProduct.WISH_PRODUCT.DATE_UPLOADED }, false);
        public static Index WISH_PRODUCT_ID = Internal.createIndex("id", WishProduct.WISH_PRODUCT, new OrderField[] { WishProduct.WISH_PRODUCT.ID }, false);
        public static Index WISH_PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", WishProduct.WISH_PRODUCT, new OrderField[] { WishProduct.WISH_PRODUCT.ID }, true);
        public static Index WISH_PRODUCT_BOOST_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", WishProductBoostDetail.WISH_PRODUCT_BOOST_DETAIL, new OrderField[] { WishProductBoostDetail.WISH_PRODUCT_BOOST_DETAIL.ID }, true);
        public static Index WISH_PRODUCT_NUMBER_SOLD_PRIMARY = Internal.createIndex("PRIMARY", WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD, new OrderField[] { WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.ID }, true);
        public static Index WISH_PRODUCT_NUMBER_SOLD_PRODUCT_ID = Internal.createIndex("product_id", WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD, new OrderField[] { WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.PRODUCT_ID }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_AUTH_CODE = Internal.createIndex("auth_code", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.AUTH_CODE }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_CREATE_DATE = Internal.createIndex("create_date", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.CREATE_DATE }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_DATE_UPLOADED = Internal.createIndex("date_uploaded", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.DATE_UPLOADED }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_INVENTORY_STATUS = Internal.createIndex("inventory_status", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.INVENTORY_STATUS }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_PARENT_SKU = Internal.createIndex("parent_sku", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.PARENT_SKU }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_PRIMARY = Internal.createIndex("PRIMARY", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.ID, WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.NUMBER_SOLD }, true);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_PRODUCT_ID = Internal.createIndex("product_id", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.PRODUCT_ID }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_DATA_VARIANT_SKU = Internal.createIndex("variant_sku", WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA, new OrderField[] { WishProductSalesMonitorData.WISH_PRODUCT_SALES_MONITOR_DATA.VARIANT_SKU }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_USER_AUTH_CODE = Internal.createIndex("auth_code", WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER, new OrderField[] { WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER.AUTH_CODE }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_USER_FILTER_STATUS = Internal.createIndex("filter_status", WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER, new OrderField[] { WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER.FILTER_STATUS }, false);
        public static Index WISH_PRODUCT_SALES_MONITOR_USER_PRIMARY = Internal.createIndex("PRIMARY", WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER, new OrderField[] { WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER.ID }, true);
        public static Index WISH_PRODUCT_SALES_MONITOR_USER_SORT = Internal.createIndex("sort", WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER, new OrderField[] { WishProductSalesMonitorUser.WISH_PRODUCT_SALES_MONITOR_USER.SORT }, false);
        public static Index WISH_SOLD_DATE_PRIMARY = Internal.createIndex("PRIMARY", WishSoldDate.WISH_SOLD_DATE, new OrderField[] { WishSoldDate.WISH_SOLD_DATE.ID }, true);
        public static Index WISH_STOCK_AUTOMATION_1 = Internal.createIndex("1", WishStockAutomation.WISH_STOCK_AUTOMATION, new OrderField[] { WishStockAutomation.WISH_STOCK_AUTOMATION.AUTH_CODE }, false);
        public static Index WISH_STOCK_AUTOMATION_2 = Internal.createIndex("2", WishStockAutomation.WISH_STOCK_AUTOMATION, new OrderField[] { WishStockAutomation.WISH_STOCK_AUTOMATION.PRODUCT_ID }, false);
        public static Index WISH_STOCK_AUTOMATION_3 = Internal.createIndex("3", WishStockAutomation.WISH_STOCK_AUTOMATION, new OrderField[] { WishStockAutomation.WISH_STOCK_AUTOMATION.CREATE_DATE }, false);
        public static Index WISH_STOCK_AUTOMATION_4 = Internal.createIndex("4", WishStockAutomation.WISH_STOCK_AUTOMATION, new OrderField[] { WishStockAutomation.WISH_STOCK_AUTOMATION.UPDATE_DATE }, false);
        public static Index WISH_STOCK_AUTOMATION_5 = Internal.createIndex("5", WishStockAutomation.WISH_STOCK_AUTOMATION, new OrderField[] { WishStockAutomation.WISH_STOCK_AUTOMATION.ENABLE }, false);
        public static Index WISH_STOCK_AUTOMATION_6 = Internal.createIndex("6", WishStockAutomation.WISH_STOCK_AUTOMATION, new OrderField[] { WishStockAutomation.WISH_STOCK_AUTOMATION.SYNC_DATE }, false);
        public static Index WISH_STOCK_AUTOMATION_PRIMARY = Internal.createIndex("PRIMARY", WishStockAutomation.WISH_STOCK_AUTOMATION, new OrderField[] { WishStockAutomation.WISH_STOCK_AUTOMATION.PRODUCT_ID }, true);
        public static Index WISH_USER_PRIMARY = Internal.createIndex("PRIMARY", WishUser.WISH_USER, new OrderField[] { WishUser.WISH_USER.ID }, true);
        public static Index WISH_VARIANT_PRIMARY = Internal.createIndex("PRIMARY", WishVariant.WISH_VARIANT, new OrderField[] { WishVariant.WISH_VARIANT.ID }, true);
        public static Index WISH_VARIANT_PRODUCT_ID = Internal.createIndex("product_id", WishVariant.WISH_VARIANT, new OrderField[] { WishVariant.WISH_VARIANT.PRODUCT_ID }, false);
        public static Index WISH_WEB_COOKIE_PRIMARY = Internal.createIndex("PRIMARY", WishWebCookie.WISH_WEB_COOKIE, new OrderField[] { WishWebCookie.WISH_WEB_COOKIE.ID }, true);
    }
}
