/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.dummy_data.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DummyProduct implements Serializable {

    private static final long serialVersionUID = 1141974962;

    private String     id;
    private String     productId;
    private String     productSku;
    private Integer    productProfitMargin;
    private BigDecimal productCost;
    private Integer    productWeight;
    private String     authcode;
    private String     colorList;
    private Timestamp  createDate;
    private Integer    orderCount;
    private String     sizeList;
    private String     orderStatus;
    private Integer    itemsProbability;
    private Integer    mergeProbability;
    private String     supplyList;
    private String     categoryId;
    private Integer    minfluctuation;
    private Integer    maxfluctuation;

    public DummyProduct() {}

    public DummyProduct(DummyProduct value) {
        this.id = value.id;
        this.productId = value.productId;
        this.productSku = value.productSku;
        this.productProfitMargin = value.productProfitMargin;
        this.productCost = value.productCost;
        this.productWeight = value.productWeight;
        this.authcode = value.authcode;
        this.colorList = value.colorList;
        this.createDate = value.createDate;
        this.orderCount = value.orderCount;
        this.sizeList = value.sizeList;
        this.orderStatus = value.orderStatus;
        this.itemsProbability = value.itemsProbability;
        this.mergeProbability = value.mergeProbability;
        this.supplyList = value.supplyList;
        this.categoryId = value.categoryId;
        this.minfluctuation = value.minfluctuation;
        this.maxfluctuation = value.maxfluctuation;
    }

    public DummyProduct(
        String     id,
        String     productId,
        String     productSku,
        Integer    productProfitMargin,
        BigDecimal productCost,
        Integer    productWeight,
        String     authcode,
        String     colorList,
        Timestamp  createDate,
        Integer    orderCount,
        String     sizeList,
        String     orderStatus,
        Integer    itemsProbability,
        Integer    mergeProbability,
        String     supplyList,
        String     categoryId,
        Integer    minfluctuation,
        Integer    maxfluctuation
    ) {
        this.id = id;
        this.productId = productId;
        this.productSku = productSku;
        this.productProfitMargin = productProfitMargin;
        this.productCost = productCost;
        this.productWeight = productWeight;
        this.authcode = authcode;
        this.colorList = colorList;
        this.createDate = createDate;
        this.orderCount = orderCount;
        this.sizeList = sizeList;
        this.orderStatus = orderStatus;
        this.itemsProbability = itemsProbability;
        this.mergeProbability = mergeProbability;
        this.supplyList = supplyList;
        this.categoryId = categoryId;
        this.minfluctuation = minfluctuation;
        this.maxfluctuation = maxfluctuation;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductSku() {
        return this.productSku;
    }

    public void setProductSku(String productSku) {
        this.productSku = productSku;
    }

    public Integer getProductProfitMargin() {
        return this.productProfitMargin;
    }

    public void setProductProfitMargin(Integer productProfitMargin) {
        this.productProfitMargin = productProfitMargin;
    }

    public BigDecimal getProductCost() {
        return this.productCost;
    }

    public void setProductCost(BigDecimal productCost) {
        this.productCost = productCost;
    }

    public Integer getProductWeight() {
        return this.productWeight;
    }

    public void setProductWeight(Integer productWeight) {
        this.productWeight = productWeight;
    }

    public String getAuthcode() {
        return this.authcode;
    }

    public void setAuthcode(String authcode) {
        this.authcode = authcode;
    }

    public String getColorList() {
        return this.colorList;
    }

    public void setColorList(String colorList) {
        this.colorList = colorList;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public Integer getOrderCount() {
        return this.orderCount;
    }

    public void setOrderCount(Integer orderCount) {
        this.orderCount = orderCount;
    }

    public String getSizeList() {
        return this.sizeList;
    }

    public void setSizeList(String sizeList) {
        this.sizeList = sizeList;
    }

    public String getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Integer getItemsProbability() {
        return this.itemsProbability;
    }

    public void setItemsProbability(Integer itemsProbability) {
        this.itemsProbability = itemsProbability;
    }

    public Integer getMergeProbability() {
        return this.mergeProbability;
    }

    public void setMergeProbability(Integer mergeProbability) {
        this.mergeProbability = mergeProbability;
    }

    public String getSupplyList() {
        return this.supplyList;
    }

    public void setSupplyList(String supplyList) {
        this.supplyList = supplyList;
    }

    public String getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getMinfluctuation() {
        return this.minfluctuation;
    }

    public void setMinfluctuation(Integer minfluctuation) {
        this.minfluctuation = minfluctuation;
    }

    public Integer getMaxfluctuation() {
        return this.maxfluctuation;
    }

    public void setMaxfluctuation(Integer maxfluctuation) {
        this.maxfluctuation = maxfluctuation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DummyProduct (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(productSku);
        sb.append(", ").append(productProfitMargin);
        sb.append(", ").append(productCost);
        sb.append(", ").append(productWeight);
        sb.append(", ").append(authcode);
        sb.append(", ").append(colorList);
        sb.append(", ").append(createDate);
        sb.append(", ").append(orderCount);
        sb.append(", ").append(sizeList);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(itemsProbability);
        sb.append(", ").append(mergeProbability);
        sb.append(", ").append(supplyList);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(minfluctuation);
        sb.append(", ").append(maxfluctuation);

        sb.append(")");
        return sb.toString();
    }
}
