/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish_api.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish_api.tables.FinanceSyncOrderStatus;


/**
 * 财务 - 同步订单状态
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FinanceSyncOrderStatusRecord extends UpdatableRecordImpl<FinanceSyncOrderStatusRecord> implements Record10<String, String, Timestamp, Boolean, String, String, Boolean, String, Integer, Integer> {

    private static final long serialVersionUID = -1252297603;

    /**
     * Setter for <code>wish_api.finance_sync_order_status.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.batch_code</code>.
     */
    public void setBatchCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.batch_code</code>.
     */
    public String getBatchCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.status</code>.
     */
    public void setStatus(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.auth_code</code>.
     */
    public void setAuthCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.auth_code</code>.
     */
    public String getAuthCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.job_id</code>.
     */
    public void setJobId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.job_id</code>.
     */
    public String getJobId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.cvs_status</code>.
     */
    public void setCvsStatus(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.cvs_status</code>.
     */
    public Boolean getCvsStatus() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.msg</code>.
     */
    public void setMsg(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.msg</code>.
     */
    public String getMsg() {
        return (String) get(7);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.count</code>.
     */
    public void setCount(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>wish_api.finance_sync_order_status.processing_time</code>.
     */
    public void setProcessingTime(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>wish_api.finance_sync_order_status.processing_time</code>.
     */
    public Integer getProcessingTime() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Timestamp, Boolean, String, String, Boolean, String, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Timestamp, Boolean, String, String, Boolean, String, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.BATCH_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.AUTH_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.JOB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.CVS_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS.PROCESSING_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBatchCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getCvsStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getProcessingTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBatchCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getCvsStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getProcessingTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value2(String value) {
        setBatchCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value3(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value4(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value5(String value) {
        setAuthCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value6(String value) {
        setJobId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value7(Boolean value) {
        setCvsStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value8(String value) {
        setMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value9(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord value10(Integer value) {
        setProcessingTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FinanceSyncOrderStatusRecord values(String value1, String value2, Timestamp value3, Boolean value4, String value5, String value6, Boolean value7, String value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FinanceSyncOrderStatusRecord
     */
    public FinanceSyncOrderStatusRecord() {
        super(FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS);
    }

    /**
     * Create a detached, initialised FinanceSyncOrderStatusRecord
     */
    public FinanceSyncOrderStatusRecord(String id, String batchCode, Timestamp createDate, Boolean status, String authCode, String jobId, Boolean cvsStatus, String msg, Integer count, Integer processingTime) {
        super(FinanceSyncOrderStatus.FINANCE_SYNC_ORDER_STATUS);

        set(0, id);
        set(1, batchCode);
        set(2, createDate);
        set(3, status);
        set(4, authCode);
        set(5, jobId);
        set(6, cvsStatus);
        set(7, msg);
        set(8, count);
        set(9, processingTime);
    }
}
