/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.dummy_data.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.dummy_data.tables.DummyConfig;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DummyConfigRecord extends UpdatableRecordImpl<DummyConfigRecord> implements Record9<String, Integer, Integer, Integer, Integer, Integer, Double, Integer, String> {

    private static final long serialVersionUID = -293584251;

    /**
     * Setter for <code>dummy_data.dummy_config.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.us_order_proportion</code>. 美国订单占比
     */
    public void setUsOrderProportion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.us_order_proportion</code>. 美国订单占比
     */
    public Integer getUsOrderProportion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.refund_order_number_benchmark</code>. 退款订单数基准
     */
    public void setRefundOrderNumberBenchmark(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.refund_order_number_benchmark</code>. 退款订单数基准
     */
    public Integer getRefundOrderNumberBenchmark() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.shipped_successfully_order_quantity_benchmark</code>. 发货成功订单数基准
     */
    public void setShippedSuccessfullyOrderQuantityBenchmark(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.shipped_successfully_order_quantity_benchmark</code>. 发货成功订单数基准
     */
    public Integer getShippedSuccessfullyOrderQuantityBenchmark() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.in_stock_count</code>.
     */
    public void setInStockCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.in_stock_count</code>.
     */
    public Integer getInStockCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.out_of_stock_count</code>.
     */
    public void setOutOfStockCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.out_of_stock_count</code>.
     */
    public Integer getOutOfStockCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.refund_rate</code>.
     */
    public void setRefundRate(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.refund_rate</code>.
     */
    public Double getRefundRate() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.waybill_number_application</code>.
     */
    public void setWaybillNumberApplication(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.waybill_number_application</code>.
     */
    public Integer getWaybillNumberApplication() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>dummy_data.dummy_config.dianxiaomi_account_name</code>.
     */
    public void setDianxiaomiAccountName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_config.dianxiaomi_account_name</code>.
     */
    public String getDianxiaomiAccountName() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Integer, Integer, Integer, Integer, Integer, Double, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Integer, Integer, Integer, Integer, Integer, Double, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DummyConfig.DUMMY_CONFIG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DummyConfig.DUMMY_CONFIG.US_ORDER_PROPORTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DummyConfig.DUMMY_CONFIG.REFUND_ORDER_NUMBER_BENCHMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DummyConfig.DUMMY_CONFIG.SHIPPED_SUCCESSFULLY_ORDER_QUANTITY_BENCHMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DummyConfig.DUMMY_CONFIG.IN_STOCK_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return DummyConfig.DUMMY_CONFIG.OUT_OF_STOCK_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return DummyConfig.DUMMY_CONFIG.REFUND_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return DummyConfig.DUMMY_CONFIG.WAYBILL_NUMBER_APPLICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DummyConfig.DUMMY_CONFIG.DIANXIAOMI_ACCOUNT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUsOrderProportion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRefundOrderNumberBenchmark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getShippedSuccessfullyOrderQuantityBenchmark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getInStockCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getOutOfStockCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getRefundRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getWaybillNumberApplication();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDianxiaomiAccountName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUsOrderProportion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRefundOrderNumberBenchmark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getShippedSuccessfullyOrderQuantityBenchmark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getInStockCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOutOfStockCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getRefundRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getWaybillNumberApplication();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDianxiaomiAccountName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value2(Integer value) {
        setUsOrderProportion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value3(Integer value) {
        setRefundOrderNumberBenchmark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value4(Integer value) {
        setShippedSuccessfullyOrderQuantityBenchmark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value5(Integer value) {
        setInStockCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value6(Integer value) {
        setOutOfStockCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value7(Double value) {
        setRefundRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value8(Integer value) {
        setWaybillNumberApplication(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord value9(String value) {
        setDianxiaomiAccountName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyConfigRecord values(String value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Double value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DummyConfigRecord
     */
    public DummyConfigRecord() {
        super(DummyConfig.DUMMY_CONFIG);
    }

    /**
     * Create a detached, initialised DummyConfigRecord
     */
    public DummyConfigRecord(String id, Integer usOrderProportion, Integer refundOrderNumberBenchmark, Integer shippedSuccessfullyOrderQuantityBenchmark, Integer inStockCount, Integer outOfStockCount, Double refundRate, Integer waybillNumberApplication, String dianxiaomiAccountName) {
        super(DummyConfig.DUMMY_CONFIG);

        set(0, id);
        set(1, usOrderProportion);
        set(2, refundOrderNumberBenchmark);
        set(3, shippedSuccessfullyOrderQuantityBenchmark);
        set(4, inStockCount);
        set(5, outOfStockCount);
        set(6, refundRate);
        set(7, waybillNumberApplication);
        set(8, dianxiaomiAccountName);
    }
}
