/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.dummy_data.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.dummy_data.tables.DummyChatgptUserName;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DummyChatgptUserNameRecord extends UpdatableRecordImpl<DummyChatgptUserNameRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -2067877187;

    /**
     * Setter for <code>dummy_data.dummy_chatgpt_user_name.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_chatgpt_user_name.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>dummy_data.dummy_chatgpt_user_name.russia_name</code>.
     */
    public void setRussiaName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dummy_data.dummy_chatgpt_user_name.russia_name</code>.
     */
    public String getRussiaName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DummyChatgptUserName.DUMMY_CHATGPT_USER_NAME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DummyChatgptUserName.DUMMY_CHATGPT_USER_NAME.RUSSIA_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRussiaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRussiaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyChatgptUserNameRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyChatgptUserNameRecord value2(String value) {
        setRussiaName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyChatgptUserNameRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DummyChatgptUserNameRecord
     */
    public DummyChatgptUserNameRecord() {
        super(DummyChatgptUserName.DUMMY_CHATGPT_USER_NAME);
    }

    /**
     * Create a detached, initialised DummyChatgptUserNameRecord
     */
    public DummyChatgptUserNameRecord(String id, String russiaName) {
        super(DummyChatgptUserName.DUMMY_CHATGPT_USER_NAME);

        set(0, id);
        set(1, russiaName);
    }
}
