/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.CostPbDianxiaomi;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CostPbDianxiaomiRecord extends UpdatableRecordImpl<CostPbDianxiaomiRecord> implements Record15<String, String, String, String, Double, Double, Integer, Integer, Double, String, String, String, String, String, String> {

    private static final long serialVersionUID = 604237506;

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.活动ID</code>.
     */
    public void set活动id(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.活动ID</code>.
     */
    public String get活动id() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.活动名称</code>.
     */
    public void set活动名称(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.活动名称</code>.
     */
    public String get活动名称() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.店铺</code>.
     */
    public void set店铺(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.店铺</code>.
     */
    public String get店铺() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.预算</code>.
     */
    public void set预算(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.预算</code>.
     */
    public Double get预算() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.费用</code>.
     */
    public void set费用(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.费用</code>.
     */
    public Double get费用() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.付费流量</code>.
     */
    public void set付费流量(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.付费流量</code>.
     */
    public Integer get付费流量() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.订单</code>.
     */
    public void set订单(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.订单</code>.
     */
    public Integer get订单() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.成交总额</code>.
     */
    public void set成交总额(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.成交总额</code>.
     */
    public Double get成交总额() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.花费成交比</code>.
     */
    public void set花费成交比(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.花费成交比</code>.
     */
    public String get花费成交比() {
        return (String) get(9);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.费用预算比</code>.
     */
    public void set费用预算比(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.费用预算比</code>.
     */
    public String get费用预算比() {
        return (String) get(10);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.开始时间</code>.
     */
    public void set开始时间(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.开始时间</code>.
     */
    public String get开始时间() {
        return (String) get(11);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.结束时间</code>.
     */
    public void set结束时间(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.结束时间</code>.
     */
    public String get结束时间() {
        return (String) get(12);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.活动状态</code>.
     */
    public void set活动状态(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.活动状态</code>.
     */
    public String get活动状态() {
        return (String) get(13);
    }

    /**
     * Setter for <code>wish.cost_pb_dianxiaomi.批次时间</code>.
     */
    public void set批次时间(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>wish.cost_pb_dianxiaomi.批次时间</code>.
     */
    public String get批次时间() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, Double, Double, Integer, Integer, Double, String, String, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, Double, Double, Integer, Integer, Double, String, String, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.活动ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.活动名称;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.店铺;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.预算;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.费用;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.付费流量;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.订单;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.成交总额;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.花费成交比;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.费用预算比;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.开始时间;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.结束时间;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.活动状态;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return CostPbDianxiaomi.COST_PB_DIANXIAOMI.批次时间;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return get活动id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return get活动名称();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return get店铺();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return get预算();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return get费用();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return get付费流量();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return get订单();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return get成交总额();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return get花费成交比();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return get费用预算比();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return get开始时间();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return get结束时间();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return get活动状态();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return get批次时间();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return get活动id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return get活动名称();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return get店铺();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return get预算();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return get费用();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return get付费流量();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return get订单();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return get成交总额();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return get花费成交比();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return get费用预算比();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return get开始时间();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return get结束时间();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return get活动状态();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return get批次时间();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value2(String value) {
        set活动id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value3(String value) {
        set活动名称(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value4(String value) {
        set店铺(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value5(Double value) {
        set预算(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value6(Double value) {
        set费用(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value7(Integer value) {
        set付费流量(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value8(Integer value) {
        set订单(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value9(Double value) {
        set成交总额(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value10(String value) {
        set花费成交比(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value11(String value) {
        set费用预算比(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value12(String value) {
        set开始时间(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value13(String value) {
        set结束时间(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value14(String value) {
        set活动状态(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord value15(String value) {
        set批次时间(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbDianxiaomiRecord values(String value1, String value2, String value3, String value4, Double value5, Double value6, Integer value7, Integer value8, Double value9, String value10, String value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CostPbDianxiaomiRecord
     */
    public CostPbDianxiaomiRecord() {
        super(CostPbDianxiaomi.COST_PB_DIANXIAOMI);
    }

    /**
     * Create a detached, initialised CostPbDianxiaomiRecord
     */
    public CostPbDianxiaomiRecord(String id, String 活动id, String 活动名称, String 店铺, Double 预算, Double 费用, Integer 付费流量, Integer 订单, Double 成交总额, String 花费成交比, String 费用预算比, String 开始时间, String 结束时间, String 活动状态, String 批次时间) {
        super(CostPbDianxiaomi.COST_PB_DIANXIAOMI);

        set(0, id);
        set(1, 活动id);
        set(2, 活动名称);
        set(3, 店铺);
        set(4, 预算);
        set(5, 费用);
        set(6, 付费流量);
        set(7, 订单);
        set(8, 成交总额);
        set(9, 花费成交比);
        set(10, 费用预算比);
        set(11, 开始时间);
        set(12, 结束时间);
        set(13, 活动状态);
        set(14, 批次时间);
    }
}
