/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.CostPbCost;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CostPbCostRecord extends UpdatableRecordImpl<CostPbCostRecord> implements Record9<String, String, Double, Double, Double, Double, String, Double, Timestamp> {

    private static final long serialVersionUID = -521682657;

    /**
     * Setter for <code>wish.cost_pb_cost.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.currentPbDate</code>.
     */
    public void setCurrentpbdate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.currentPbDate</code>.
     */
    public String getCurrentpbdate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.totalOrder</code>.
     */
    public void setTotalorder(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.totalOrder</code>.
     */
    public Double getTotalorder() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.totalTurnover</code>.
     */
    public void setTotalturnover(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.totalTurnover</code>.
     */
    public Double getTotalturnover() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.wishCoat</code>.
     */
    public void setWishcoat(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.wishCoat</code>.
     */
    public Double getWishcoat() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.systemCoat</code>.
     */
    public void setSystemcoat(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.systemCoat</code>.
     */
    public Double getSystemcoat() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.dianXiaoMiPBId</code>.
     */
    public void setDianxiaomipbid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.dianXiaoMiPBId</code>.
     */
    public String getDianxiaomipbid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.totalCost</code>.
     */
    public void setTotalcost(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.totalCost</code>.
     */
    public Double getTotalcost() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>wish.cost_pb_cost.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>wish.cost_pb_cost.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Double, Double, Double, Double, String, Double, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Double, Double, Double, Double, String, Double, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CostPbCost.COST_PB_COST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CostPbCost.COST_PB_COST.CURRENTPBDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return CostPbCost.COST_PB_COST.TOTALORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return CostPbCost.COST_PB_COST.TOTALTURNOVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return CostPbCost.COST_PB_COST.WISHCOAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return CostPbCost.COST_PB_COST.SYSTEMCOAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CostPbCost.COST_PB_COST.DIANXIAOMIPBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return CostPbCost.COST_PB_COST.TOTALCOST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return CostPbCost.COST_PB_COST.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCurrentpbdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getTotalorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getTotalturnover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getWishcoat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getSystemcoat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDianxiaomipbid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getTotalcost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCurrentpbdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getTotalorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getTotalturnover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getWishcoat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getSystemcoat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDianxiaomipbid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getTotalcost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value2(String value) {
        setCurrentpbdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value3(Double value) {
        setTotalorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value4(Double value) {
        setTotalturnover(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value5(Double value) {
        setWishcoat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value6(Double value) {
        setSystemcoat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value7(String value) {
        setDianxiaomipbid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value8(Double value) {
        setTotalcost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord value9(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CostPbCostRecord values(String value1, String value2, Double value3, Double value4, Double value5, Double value6, String value7, Double value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CostPbCostRecord
     */
    public CostPbCostRecord() {
        super(CostPbCost.COST_PB_COST);
    }

    /**
     * Create a detached, initialised CostPbCostRecord
     */
    public CostPbCostRecord(String id, String currentpbdate, Double totalorder, Double totalturnover, Double wishcoat, Double systemcoat, String dianxiaomipbid, Double totalcost, Timestamp createdate) {
        super(CostPbCost.COST_PB_COST);

        set(0, id);
        set(1, currentpbdate);
        set(2, totalorder);
        set(3, totalturnover);
        set(4, wishcoat);
        set(5, systemcoat);
        set(6, dianxiaomipbid);
        set(7, totalcost);
        set(8, createdate);
    }
}
