/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.Customizeinfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomizeinfoRecord extends UpdatableRecordImpl<CustomizeinfoRecord> implements Record7<String, String, Integer, String, Timestamp, String, String> {

    private static final long serialVersionUID = 949223098;

    /**
     * Setter for <code>wish.customizeInfo.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.customizeInfo.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.customizeInfo.productSize</code>.
     */
    public void setProductsize(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.customizeInfo.productSize</code>.
     */
    public String getProductsize() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.customizeInfo.count</code>.
     */
    public void setCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.customizeInfo.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>wish.customizeInfo.customizeProductId</code>.
     */
    public void setCustomizeproductid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.customizeInfo.customizeProductId</code>.
     */
    public String getCustomizeproductid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wish.customizeInfo.createTime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.customizeInfo.createTime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>wish.customizeInfo.searchDate</code>.
     */
    public void setSearchdate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.customizeInfo.searchDate</code>.
     */
    public String getSearchdate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>wish.customizeInfo.mark</code>.
     */
    public void setMark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.customizeInfo.mark</code>.
     */
    public String getMark() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, String, Timestamp, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, String, Timestamp, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Customizeinfo.CUSTOMIZEINFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Customizeinfo.CUSTOMIZEINFO.PRODUCTSIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Customizeinfo.CUSTOMIZEINFO.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Customizeinfo.CUSTOMIZEINFO.CUSTOMIZEPRODUCTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Customizeinfo.CUSTOMIZEINFO.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Customizeinfo.CUSTOMIZEINFO.SEARCHDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Customizeinfo.CUSTOMIZEINFO.MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductsize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCustomizeproductid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSearchdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductsize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCustomizeproductid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSearchdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord value2(String value) {
        setProductsize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord value3(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord value4(String value) {
        setCustomizeproductid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord value5(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord value6(String value) {
        setSearchdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord value7(String value) {
        setMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeinfoRecord values(String value1, String value2, Integer value3, String value4, Timestamp value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomizeinfoRecord
     */
    public CustomizeinfoRecord() {
        super(Customizeinfo.CUSTOMIZEINFO);
    }

    /**
     * Create a detached, initialised CustomizeinfoRecord
     */
    public CustomizeinfoRecord(String id, String productsize, Integer count, String customizeproductid, Timestamp createtime, String searchdate, String mark) {
        super(Customizeinfo.CUSTOMIZEINFO);

        set(0, id);
        set(1, productsize);
        set(2, count);
        set(3, customizeproductid);
        set(4, createtime);
        set(5, searchdate);
        set(6, mark);
    }
}
