/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.Customizeproduct;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomizeproductRecord extends UpdatableRecordImpl<CustomizeproductRecord> implements Record8<String, String, String, String, String, Timestamp, String, String> {

    private static final long serialVersionUID = -113666900;

    /**
     * Setter for <code>wish.customizeProduct.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.customizeProduct.backImageUrl</code>.
     */
    public void setBackimageurl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.backImageUrl</code>.
     */
    public String getBackimageurl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.customizeProduct.imageUrl</code>.
     */
    public void setImageurl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.imageUrl</code>.
     */
    public String getImageurl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wish.customizeProduct.productSku</code>.
     */
    public void setProductsku(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.productSku</code>.
     */
    public String getProductsku() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wish.customizeProduct.productId</code>.
     */
    public void setProductid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.productId</code>.
     */
    public String getProductid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wish.customizeProduct.createTime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.createTime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>wish.customizeProduct.provider</code>.
     */
    public void setProvider(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.provider</code>.
     */
    public String getProvider() {
        return (String) get(6);
    }

    /**
     * Setter for <code>wish.customizeProduct.mark</code>.
     */
    public void setMark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.customizeProduct.mark</code>.
     */
    public String getMark() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, Timestamp, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, Timestamp, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Customizeproduct.CUSTOMIZEPRODUCT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Customizeproduct.CUSTOMIZEPRODUCT.BACKIMAGEURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Customizeproduct.CUSTOMIZEPRODUCT.IMAGEURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Customizeproduct.CUSTOMIZEPRODUCT.PRODUCTSKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Customizeproduct.CUSTOMIZEPRODUCT.PRODUCTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Customizeproduct.CUSTOMIZEPRODUCT.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Customizeproduct.CUSTOMIZEPRODUCT.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Customizeproduct.CUSTOMIZEPRODUCT.MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBackimageurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImageurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProductsku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProductid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBackimageurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImageurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProductsku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProductid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value2(String value) {
        setBackimageurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value3(String value) {
        setImageurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value4(String value) {
        setProductsku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value5(String value) {
        setProductid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value6(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value7(String value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord value8(String value) {
        setMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomizeproductRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomizeproductRecord
     */
    public CustomizeproductRecord() {
        super(Customizeproduct.CUSTOMIZEPRODUCT);
    }

    /**
     * Create a detached, initialised CustomizeproductRecord
     */
    public CustomizeproductRecord(String id, String backimageurl, String imageurl, String productsku, String productid, Timestamp createtime, String provider, String mark) {
        super(Customizeproduct.CUSTOMIZEPRODUCT);

        set(0, id);
        set(1, backimageurl);
        set(2, imageurl);
        set(3, productsku);
        set(4, productid);
        set(5, createtime);
        set(6, provider);
        set(7, mark);
    }
}
