/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.JzmPurchaseOrder;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JzmPurchaseOrderRecord extends UpdatableRecordImpl<JzmPurchaseOrderRecord> implements Record11<String, Timestamp, String, String, String, Integer, String, Integer, Boolean, String, Boolean> {

    private static final long serialVersionUID = -1800165050;

    /**
     * Setter for <code>wish.jzm_purchase_order.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.product_sku</code>.
     */
    public void setProductSku(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.product_sku</code>.
     */
    public String getProductSku() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.sku_code</code>.
     */
    public void setSkuCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.sku_code</code>.
     */
    public String getSkuCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.code</code>.
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.code</code>.
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.count</code>.
     */
    public void setCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.size</code>.
     */
    public void setSize(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.size</code>.
     */
    public String getSize() {
        return (String) get(6);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.max_count</code>.
     */
    public void setMaxCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.max_count</code>.
     */
    public Integer getMaxCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.is_generate</code>. 是否生成采购单
     */
    public void setIsGenerate(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.is_generate</code>. 是否生成采购单
     */
    public Boolean getIsGenerate() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.warehouse_order_code</code>.
     */
    public void setWarehouseOrderCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.warehouse_order_code</code>.
     */
    public String getWarehouseOrderCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>wish.jzm_purchase_order.is_close</code>.
     */
    public void setIsClose(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>wish.jzm_purchase_order.is_close</code>.
     */
    public Boolean getIsClose() {
        return (Boolean) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, Timestamp, String, String, String, Integer, String, Integer, Boolean, String, Boolean> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, Timestamp, String, String, String, Integer, String, Integer, Boolean, String, Boolean> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.PRODUCT_SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.SKU_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.MAX_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.IS_GENERATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.WAREHOUSE_ORDER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return JzmPurchaseOrder.JZM_PURCHASE_ORDER.IS_CLOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProductSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSkuCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getMaxCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getIsGenerate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getWarehouseOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getIsClose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProductSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSkuCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getMaxCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsGenerate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getWarehouseOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getIsClose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value2(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value3(String value) {
        setProductSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value4(String value) {
        setSkuCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value5(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value6(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value7(String value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value8(Integer value) {
        setMaxCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value9(Boolean value) {
        setIsGenerate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value10(String value) {
        setWarehouseOrderCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord value11(Boolean value) {
        setIsClose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JzmPurchaseOrderRecord values(String value1, Timestamp value2, String value3, String value4, String value5, Integer value6, String value7, Integer value8, Boolean value9, String value10, Boolean value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JzmPurchaseOrderRecord
     */
    public JzmPurchaseOrderRecord() {
        super(JzmPurchaseOrder.JZM_PURCHASE_ORDER);
    }

    /**
     * Create a detached, initialised JzmPurchaseOrderRecord
     */
    public JzmPurchaseOrderRecord(String id, Timestamp createDate, String productSku, String skuCode, String code, Integer count, String size, Integer maxCount, Boolean isGenerate, String warehouseOrderCode, Boolean isClose) {
        super(JzmPurchaseOrder.JZM_PURCHASE_ORDER);

        set(0, id);
        set(1, createDate);
        set(2, productSku);
        set(3, skuCode);
        set(4, code);
        set(5, count);
        set(6, size);
        set(7, maxCount);
        set(8, isGenerate);
        set(9, warehouseOrderCode);
        set(10, isClose);
    }
}
