/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.Productinfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductinfoRecord extends UpdatableRecordImpl<ProductinfoRecord> implements Record4<String, String, Integer, Timestamp> {

    private static final long serialVersionUID = -1079786236;

    /**
     * Setter for <code>wish.productInfo.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.productInfo.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.productInfo.productId</code>.
     */
    public void setProductid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.productInfo.productId</code>.
     */
    public String getProductid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.productInfo.purchaseNumber</code>.
     */
    public void setPurchasenumber(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.productInfo.purchaseNumber</code>.
     */
    public Integer getPurchasenumber() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>wish.productInfo.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.productInfo.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Productinfo.PRODUCTINFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Productinfo.PRODUCTINFO.PRODUCTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Productinfo.PRODUCTINFO.PURCHASENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Productinfo.PRODUCTINFO.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPurchasenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPurchasenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductinfoRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductinfoRecord value2(String value) {
        setProductid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductinfoRecord value3(Integer value) {
        setPurchasenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductinfoRecord value4(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductinfoRecord values(String value1, String value2, Integer value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductinfoRecord
     */
    public ProductinfoRecord() {
        super(Productinfo.PRODUCTINFO);
    }

    /**
     * Create a detached, initialised ProductinfoRecord
     */
    public ProductinfoRecord(String id, String productid, Integer purchasenumber, Timestamp createdate) {
        super(Productinfo.PRODUCTINFO);

        set(0, id);
        set(1, productid);
        set(2, purchasenumber);
        set(3, createdate);
    }
}
