/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.ProductSalesMonitor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductSalesMonitorRecord extends UpdatableRecordImpl<ProductSalesMonitorRecord> implements Record9<String, String, String, Integer, String, String, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = 1085311530;

    /**
     * Setter for <code>wish.product_sales_monitor.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.product_id</code>.
     */
    public void setProductId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.product_id</code>.
     */
    public String getProductId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.shop</code>.
     */
    public void setShop(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.shop</code>.
     */
    public String getShop() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.num</code>.
     */
    public void setNum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.image_src</code>.
     */
    public void setImageSrc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.image_src</code>.
     */
    public String getImageSrc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.parent_sku</code>.
     */
    public void setParentSku(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.parent_sku</code>.
     */
    public String getParentSku() {
        return (String) get(5);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.shelf_date</code>.
     */
    public void setShelfDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.shelf_date</code>.
     */
    public Timestamp getShelfDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>wish.product_sales_monitor.sales_num</code>.
     */
    public void setSalesNum(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>wish.product_sales_monitor.sales_num</code>.
     */
    public Integer getSalesNum() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Integer, String, String, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Integer, String, String, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.SHOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.IMAGE_SRC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.PARENT_SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.SHELF_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return ProductSalesMonitor.PRODUCT_SALES_MONITOR.SALES_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getShop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getImageSrc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getParentSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getShelfDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getSalesNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getShop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImageSrc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getParentSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getShelfDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSalesNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value2(String value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value3(String value) {
        setShop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value4(Integer value) {
        setNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value5(String value) {
        setImageSrc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value6(String value) {
        setParentSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value7(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value8(Timestamp value) {
        setShelfDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord value9(Integer value) {
        setSalesNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductSalesMonitorRecord values(String value1, String value2, String value3, Integer value4, String value5, String value6, Timestamp value7, Timestamp value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductSalesMonitorRecord
     */
    public ProductSalesMonitorRecord() {
        super(ProductSalesMonitor.PRODUCT_SALES_MONITOR);
    }

    /**
     * Create a detached, initialised ProductSalesMonitorRecord
     */
    public ProductSalesMonitorRecord(String id, String productId, String shop, Integer num, String imageSrc, String parentSku, Timestamp createDate, Timestamp shelfDate, Integer salesNum) {
        super(ProductSalesMonitor.PRODUCT_SALES_MONITOR);

        set(0, id);
        set(1, productId);
        set(2, shop);
        set(3, num);
        set(4, imageSrc);
        set(5, parentSku);
        set(6, createDate);
        set(7, shelfDate);
        set(8, salesNum);
    }
}
