/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.SmsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmsRecordRecord extends UpdatableRecordImpl<SmsRecordRecord> implements Record7<String, Timestamp, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = -354237528;

    /**
     * Setter for <code>wish.sms_record.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.sms_record.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.sms_record.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.sms_record.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>wish.sms_record.sms_verification_code_id</code>.
     */
    public void setSmsVerificationCodeId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.sms_record.sms_verification_code_id</code>.
     */
    public String getSmsVerificationCodeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wish.sms_record.target_number</code>.
     */
    public void setTargetNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.sms_record.target_number</code>.
     */
    public String getTargetNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wish.sms_record.state</code>.
     */
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.sms_record.state</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wish.sms_record.send_date</code>.
     */
    public void setSendDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.sms_record.send_date</code>.
     */
    public Timestamp getSendDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>wish.sms_record.response</code>.
     */
    public void setResponse(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.sms_record.response</code>.
     */
    public String getResponse() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Timestamp, String, String, String, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Timestamp, String, String, String, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SmsRecord.SMS_RECORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return SmsRecord.SMS_RECORD.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SmsRecord.SMS_RECORD.SMS_VERIFICATION_CODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SmsRecord.SMS_RECORD.TARGET_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SmsRecord.SMS_RECORD.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return SmsRecord.SMS_RECORD.SEND_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SmsRecord.SMS_RECORD.RESPONSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSmsVerificationCodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTargetNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getResponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSmsVerificationCodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTargetNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getResponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord value2(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord value3(String value) {
        setSmsVerificationCodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord value4(String value) {
        setTargetNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord value5(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord value6(Timestamp value) {
        setSendDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord value7(String value) {
        setResponse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmsRecordRecord values(String value1, Timestamp value2, String value3, String value4, String value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmsRecordRecord
     */
    public SmsRecordRecord() {
        super(SmsRecord.SMS_RECORD);
    }

    /**
     * Create a detached, initialised SmsRecordRecord
     */
    public SmsRecordRecord(String id, Timestamp createDate, String smsVerificationCodeId, String targetNumber, String state, Timestamp sendDate, String response) {
        super(SmsRecord.SMS_RECORD);

        set(0, id);
        set(1, createDate);
        set(2, smsVerificationCodeId);
        set(3, targetNumber);
        set(4, state);
        set(5, sendDate);
        set(6, response);
    }
}
