/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.WebsiteAddress;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebsiteAddressRecord extends UpdatableRecordImpl<WebsiteAddressRecord> implements Record5<String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1332100011;

    /**
     * Setter for <code>wish.website_address.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.website_address.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.website_address.domainNname</code>.
     */
    public void setDomainnname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.website_address.domainNname</code>.
     */
    public String getDomainnname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.website_address.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.website_address.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wish.website_address.remark</code>.
     */
    public void setRemark(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.website_address.remark</code>.
     */
    public String getRemark() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wish.website_address.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.website_address.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return WebsiteAddress.WEBSITE_ADDRESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WebsiteAddress.WEBSITE_ADDRESS.DOMAINNNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WebsiteAddress.WEBSITE_ADDRESS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WebsiteAddress.WEBSITE_ADDRESS.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return WebsiteAddress.WEBSITE_ADDRESS.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDomainnname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDomainnname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebsiteAddressRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebsiteAddressRecord value2(String value) {
        setDomainnname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebsiteAddressRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebsiteAddressRecord value4(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebsiteAddressRecord value5(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebsiteAddressRecord values(String value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebsiteAddressRecord
     */
    public WebsiteAddressRecord() {
        super(WebsiteAddress.WEBSITE_ADDRESS);
    }

    /**
     * Create a detached, initialised WebsiteAddressRecord
     */
    public WebsiteAddressRecord(String id, String domainnname, String type, String remark, Timestamp createdate) {
        super(WebsiteAddress.WEBSITE_ADDRESS);

        set(0, id);
        set(1, domainnname);
        set(2, type);
        set(3, remark);
        set(4, createdate);
    }
}
