/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.WishWebCookie;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishWebCookieRecord extends UpdatableRecordImpl<WishWebCookieRecord> implements Record3<String, Timestamp, String> {

    private static final long serialVersionUID = -1457257042;

    /**
     * Setter for <code>wish.wish_web_cookie.cookies</code>.
     */
    public void setCookies(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.wish_web_cookie.cookies</code>.
     */
    public String getCookies() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.wish_web_cookie.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.wish_web_cookie.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>wish.wish_web_cookie.id</code>.
     */
    public void setId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.wish_web_cookie.id</code>.
     */
    public String getId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return WishWebCookie.WISH_WEB_COOKIE.COOKIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return WishWebCookie.WISH_WEB_COOKIE.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WishWebCookie.WISH_WEB_COOKIE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getCookies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCookies();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishWebCookieRecord value1(String value) {
        setCookies(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishWebCookieRecord value2(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishWebCookieRecord value3(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishWebCookieRecord values(String value1, Timestamp value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WishWebCookieRecord
     */
    public WishWebCookieRecord() {
        super(WishWebCookie.WISH_WEB_COOKIE);
    }

    /**
     * Create a detached, initialised WishWebCookieRecord
     */
    public WishWebCookieRecord(String cookies, Timestamp createdate, String id) {
        super(WishWebCookie.WISH_WEB_COOKIE);

        set(0, cookies);
        set(1, createdate);
        set(2, id);
    }
}
