/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.WishProductNumberSold;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishProductNumberSoldRecord extends UpdatableRecordImpl<WishProductNumberSoldRecord> implements Record8<String, String, Integer, Integer, Timestamp, String, String, Timestamp> {

    private static final long serialVersionUID = -525536458;

    /**
     * Setter for <code>wish.wish_product_number_sold.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.wish_product_number_sold.product_id</code>.
     */
    public void setProductId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.product_id</code>.
     */
    public String getProductId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.wish_product_number_sold.numberSold</code>.
     */
    public void setNumbersold(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.numberSold</code>.
     */
    public Integer getNumbersold() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>wish.wish_product_number_sold.numberSaves</code>.
     */
    public void setNumbersaves(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.numberSaves</code>.
     */
    public Integer getNumbersaves() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>wish.wish_product_number_sold.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>wish.wish_product_number_sold.searchDate</code>.
     */
    public void setSearchdate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.searchDate</code>.
     */
    public String getSearchdate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>wish.wish_product_number_sold.sold_date_id</code>.
     */
    public void setSoldDateId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.sold_date_id</code>.
     */
    public String getSoldDateId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>wish.wish_product_number_sold.date_uploaded</code>.
     */
    public void setDateUploaded(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.wish_product_number_sold.date_uploaded</code>.
     */
    public Timestamp getDateUploaded() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, Integer, Timestamp, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, Integer, Timestamp, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.NUMBERSOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.NUMBERSAVES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.SEARCHDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.SOLD_DATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD.DATE_UPLOADED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getNumbersold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getNumbersaves();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSearchdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSoldDateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDateUploaded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNumbersold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNumbersaves();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSearchdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSoldDateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDateUploaded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value2(String value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value3(Integer value) {
        setNumbersold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value4(Integer value) {
        setNumbersaves(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value5(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value6(String value) {
        setSearchdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value7(String value) {
        setSoldDateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord value8(Timestamp value) {
        setDateUploaded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishProductNumberSoldRecord values(String value1, String value2, Integer value3, Integer value4, Timestamp value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WishProductNumberSoldRecord
     */
    public WishProductNumberSoldRecord() {
        super(WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD);
    }

    /**
     * Create a detached, initialised WishProductNumberSoldRecord
     */
    public WishProductNumberSoldRecord(String id, String productId, Integer numbersold, Integer numbersaves, Timestamp createdate, String searchdate, String soldDateId, Timestamp dateUploaded) {
        super(WishProductNumberSold.WISH_PRODUCT_NUMBER_SOLD);

        set(0, id);
        set(1, productId);
        set(2, numbersold);
        set(3, numbersaves);
        set(4, createdate);
        set(5, searchdate);
        set(6, soldDateId);
        set(7, dateUploaded);
    }
}
