/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.WishStockAutomation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishStockAutomationRecord extends UpdatableRecordImpl<WishStockAutomationRecord> implements Record10<String, String, Timestamp, Timestamp, String, Boolean, Integer, Integer, Timestamp, Boolean> {

    private static final long serialVersionUID = 2059460550;

    /**
     * Setter for <code>wish.wish_stock_automation.product_id</code>.
     */
    public void setProductId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.product_id</code>.
     */
    public String getProductId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.auth_code</code>.
     */
    public void setAuthCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.auth_code</code>.
     */
    public String getAuthCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.update_date</code>.
     */
    public void setUpdateDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.update_date</code>.
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.sku</code>.
     */
    public void setSku(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.sku</code>.
     */
    public String getSku() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.enable</code>.
     */
    public void setEnable(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.enable</code>.
     */
    public Boolean getEnable() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.add_stock</code>.
     */
    public void setAddStock(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.add_stock</code>.
     */
    public Integer getAddStock() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.stock_threshold</code>.
     */
    public void setStockThreshold(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.stock_threshold</code>.
     */
    public Integer getStockThreshold() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.sync_date</code>.
     */
    public void setSyncDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.sync_date</code>.
     */
    public Timestamp getSyncDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>wish.wish_stock_automation.code</code>.
     */
    public void setCode(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>wish.wish_stock_automation.code</code>.
     */
    public Boolean getCode() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Timestamp, Timestamp, String, Boolean, Integer, Integer, Timestamp, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Timestamp, Timestamp, String, Boolean, Integer, Integer, Timestamp, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.AUTH_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.ADD_STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.STOCK_THRESHOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.SYNC_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return WishStockAutomation.WISH_STOCK_AUTOMATION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getAddStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getStockThreshold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getSyncDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getAddStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStockThreshold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getSyncDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value1(String value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value2(String value) {
        setAuthCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value3(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value4(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value5(String value) {
        setSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value6(Boolean value) {
        setEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value7(Integer value) {
        setAddStock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value8(Integer value) {
        setStockThreshold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value9(Timestamp value) {
        setSyncDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord value10(Boolean value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishStockAutomationRecord values(String value1, String value2, Timestamp value3, Timestamp value4, String value5, Boolean value6, Integer value7, Integer value8, Timestamp value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WishStockAutomationRecord
     */
    public WishStockAutomationRecord() {
        super(WishStockAutomation.WISH_STOCK_AUTOMATION);
    }

    /**
     * Create a detached, initialised WishStockAutomationRecord
     */
    public WishStockAutomationRecord(String productId, String authCode, Timestamp createDate, Timestamp updateDate, String sku, Boolean enable, Integer addStock, Integer stockThreshold, Timestamp syncDate, Boolean code) {
        super(WishStockAutomation.WISH_STOCK_AUTOMATION);

        set(0, productId);
        set(1, authCode);
        set(2, createDate);
        set(3, updateDate);
        set(4, sku);
        set(5, enable);
        set(6, addStock);
        set(7, stockThreshold);
        set(8, syncDate);
        set(9, code);
    }
}
