/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;

import tanggod.github.io.config.database.repository.wish.tables.WishViolation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishViolationRecord extends TableRecordImpl<WishViolationRecord> implements Record10<Double, String, Timestamp, Timestamp, String, String, String, String, String, String> {

    private static final long serialVersionUID = -52266379;

    /**
     * Setter for <code>wish.wish_violation.fine_amount</code>.
     */
    public void setFineAmount(Double value) {
        set(0, value);
    }

    /**
     * Getter for <code>wish.wish_violation.fine_amount</code>.
     */
    public Double getFineAmount() {
        return (Double) get(0);
    }

    /**
     * Setter for <code>wish.wish_violation.reason</code>.
     */
    public void setReason(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wish.wish_violation.reason</code>.
     */
    public String getReason() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wish.wish_violation.last_updated</code>.
     */
    public void setLastUpdated(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>wish.wish_violation.last_updated</code>.
     */
    public Timestamp getLastUpdated() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>wish.wish_violation.created_time</code>.
     */
    public void setCreatedTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>wish.wish_violation.created_time</code>.
     */
    public Timestamp getCreatedTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>wish.wish_violation.state</code>.
     */
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wish.wish_violation.state</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wish.wish_violation.message</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>wish.wish_violation.message</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>wish.wish_violation.proof_type</code>.
     */
    public void setProofType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wish.wish_violation.proof_type</code>.
     */
    public String getProofType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>wish.wish_violation.product_id</code>.
     */
    public void setProductId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>wish.wish_violation.product_id</code>.
     */
    public String getProductId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>wish.wish_violation.id</code>.
     */
    public void setId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>wish.wish_violation.id</code>.
     */
    public String getId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>wish.wish_violation.auth_code</code>.
     */
    public void setAuthCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>wish.wish_violation.auth_code</code>.
     */
    public String getAuthCode() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Double, String, Timestamp, Timestamp, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Double, String, Timestamp, Timestamp, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field1() {
        return WishViolation.WISH_VIOLATION.FINE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WishViolation.WISH_VIOLATION.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return WishViolation.WISH_VIOLATION.LAST_UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return WishViolation.WISH_VIOLATION.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WishViolation.WISH_VIOLATION.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return WishViolation.WISH_VIOLATION.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return WishViolation.WISH_VIOLATION.PROOF_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return WishViolation.WISH_VIOLATION.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return WishViolation.WISH_VIOLATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return WishViolation.WISH_VIOLATION.AUTH_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component1() {
        return getFineAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getProofType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value1() {
        return getFineAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProofType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAuthCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value1(Double value) {
        setFineAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value2(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value3(Timestamp value) {
        setLastUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value4(Timestamp value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value5(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value6(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value7(String value) {
        setProofType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value8(String value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value9(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord value10(String value) {
        setAuthCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WishViolationRecord values(Double value1, String value2, Timestamp value3, Timestamp value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WishViolationRecord
     */
    public WishViolationRecord() {
        super(WishViolation.WISH_VIOLATION);
    }

    /**
     * Create a detached, initialised WishViolationRecord
     */
    public WishViolationRecord(Double fineAmount, String reason, Timestamp lastUpdated, Timestamp createdTime, String state, String message, String proofType, String productId, String id, String authCode) {
        super(WishViolation.WISH_VIOLATION);

        set(0, fineAmount);
        set(1, reason);
        set(2, lastUpdated);
        set(3, createdTime);
        set(4, state);
        set(5, message);
        set(6, proofType);
        set(7, productId);
        set(8, id);
        set(9, authCode);
    }
}
