/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Announcement implements Serializable {

    private static final long serialVersionUID = 634482620;

    private String  id;
    private String  text;
    private Integer sort;

    public Announcement() {}

    public Announcement(Announcement value) {
        this.id = value.id;
        this.text = value.text;
        this.sort = value.sort;
    }

    public Announcement(
        String  id,
        String  text,
        Integer sort
    ) {
        this.id = id;
        this.text = text;
        this.sort = sort;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Announcement (");

        sb.append(id);
        sb.append(", ").append(text);
        sb.append(", ").append(sort);

        sb.append(")");
        return sb.toString();
    }
}
