/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryDataDataAnalysisSync implements Serializable {

    private static final long serialVersionUID = 1484036402;

    private String id;
    private String syncCode;
    private String categoryIdSet;

    public CategoryDataDataAnalysisSync() {}

    public CategoryDataDataAnalysisSync(CategoryDataDataAnalysisSync value) {
        this.id = value.id;
        this.syncCode = value.syncCode;
        this.categoryIdSet = value.categoryIdSet;
    }

    public CategoryDataDataAnalysisSync(
        String id,
        String syncCode,
        String categoryIdSet
    ) {
        this.id = id;
        this.syncCode = syncCode;
        this.categoryIdSet = categoryIdSet;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSyncCode() {
        return this.syncCode;
    }

    public void setSyncCode(String syncCode) {
        this.syncCode = syncCode;
    }

    public String getCategoryIdSet() {
        return this.categoryIdSet;
    }

    public void setCategoryIdSet(String categoryIdSet) {
        this.categoryIdSet = categoryIdSet;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CategoryDataDataAnalysisSync (");

        sb.append(id);
        sb.append(", ").append(syncCode);
        sb.append(", ").append(categoryIdSet);

        sb.append(")");
        return sb.toString();
    }
}
