/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionDataParameter implements Serializable {

    private static final long serialVersionUID = -352774596;

    private String    id;
    private String    productid;
    private String    productsku;
    private Integer   weight;
    private Double    purchaseCost;
    private Double    factoryCost;
    private Double    wishPrice;
    private Double    profitRmb;
    private Double    productboostCost;
    private String    remark;
    private String    sameProduct;
    private String    collectionDataUserId;
    private Timestamp createDate;
    private Timestamp updateDate;

    public CollectionDataParameter() {}

    public CollectionDataParameter(CollectionDataParameter value) {
        this.id = value.id;
        this.productid = value.productid;
        this.productsku = value.productsku;
        this.weight = value.weight;
        this.purchaseCost = value.purchaseCost;
        this.factoryCost = value.factoryCost;
        this.wishPrice = value.wishPrice;
        this.profitRmb = value.profitRmb;
        this.productboostCost = value.productboostCost;
        this.remark = value.remark;
        this.sameProduct = value.sameProduct;
        this.collectionDataUserId = value.collectionDataUserId;
        this.createDate = value.createDate;
        this.updateDate = value.updateDate;
    }

    public CollectionDataParameter(
        String    id,
        String    productid,
        String    productsku,
        Integer   weight,
        Double    purchaseCost,
        Double    factoryCost,
        Double    wishPrice,
        Double    profitRmb,
        Double    productboostCost,
        String    remark,
        String    sameProduct,
        String    collectionDataUserId,
        Timestamp createDate,
        Timestamp updateDate
    ) {
        this.id = id;
        this.productid = productid;
        this.productsku = productsku;
        this.weight = weight;
        this.purchaseCost = purchaseCost;
        this.factoryCost = factoryCost;
        this.wishPrice = wishPrice;
        this.profitRmb = profitRmb;
        this.productboostCost = productboostCost;
        this.remark = remark;
        this.sameProduct = sameProduct;
        this.collectionDataUserId = collectionDataUserId;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProductid() {
        return this.productid;
    }

    public void setProductid(String productid) {
        this.productid = productid;
    }

    public String getProductsku() {
        return this.productsku;
    }

    public void setProductsku(String productsku) {
        this.productsku = productsku;
    }

    public Integer getWeight() {
        return this.weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Double getPurchaseCost() {
        return this.purchaseCost;
    }

    public void setPurchaseCost(Double purchaseCost) {
        this.purchaseCost = purchaseCost;
    }

    public Double getFactoryCost() {
        return this.factoryCost;
    }

    public void setFactoryCost(Double factoryCost) {
        this.factoryCost = factoryCost;
    }

    public Double getWishPrice() {
        return this.wishPrice;
    }

    public void setWishPrice(Double wishPrice) {
        this.wishPrice = wishPrice;
    }

    public Double getProfitRmb() {
        return this.profitRmb;
    }

    public void setProfitRmb(Double profitRmb) {
        this.profitRmb = profitRmb;
    }

    public Double getProductboostCost() {
        return this.productboostCost;
    }

    public void setProductboostCost(Double productboostCost) {
        this.productboostCost = productboostCost;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSameProduct() {
        return this.sameProduct;
    }

    public void setSameProduct(String sameProduct) {
        this.sameProduct = sameProduct;
    }

    public String getCollectionDataUserId() {
        return this.collectionDataUserId;
    }

    public void setCollectionDataUserId(String collectionDataUserId) {
        this.collectionDataUserId = collectionDataUserId;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CollectionDataParameter (");

        sb.append(id);
        sb.append(", ").append(productid);
        sb.append(", ").append(productsku);
        sb.append(", ").append(weight);
        sb.append(", ").append(purchaseCost);
        sb.append(", ").append(factoryCost);
        sb.append(", ").append(wishPrice);
        sb.append(", ").append(profitRmb);
        sb.append(", ").append(productboostCost);
        sb.append(", ").append(remark);
        sb.append(", ").append(sameProduct);
        sb.append(", ").append(collectionDataUserId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateDate);

        sb.append(")");
        return sb.toString();
    }
}
