/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customizeinfo implements Serializable {

    private static final long serialVersionUID = 452591103;

    private String    id;
    private String    productsize;
    private Integer   count;
    private String    customizeproductid;
    private Timestamp createtime;
    private String    searchdate;
    private String    mark;

    public Customizeinfo() {}

    public Customizeinfo(Customizeinfo value) {
        this.id = value.id;
        this.productsize = value.productsize;
        this.count = value.count;
        this.customizeproductid = value.customizeproductid;
        this.createtime = value.createtime;
        this.searchdate = value.searchdate;
        this.mark = value.mark;
    }

    public Customizeinfo(
        String    id,
        String    productsize,
        Integer   count,
        String    customizeproductid,
        Timestamp createtime,
        String    searchdate,
        String    mark
    ) {
        this.id = id;
        this.productsize = productsize;
        this.count = count;
        this.customizeproductid = customizeproductid;
        this.createtime = createtime;
        this.searchdate = searchdate;
        this.mark = mark;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProductsize() {
        return this.productsize;
    }

    public void setProductsize(String productsize) {
        this.productsize = productsize;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getCustomizeproductid() {
        return this.customizeproductid;
    }

    public void setCustomizeproductid(String customizeproductid) {
        this.customizeproductid = customizeproductid;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    public String getSearchdate() {
        return this.searchdate;
    }

    public void setSearchdate(String searchdate) {
        this.searchdate = searchdate;
    }

    public String getMark() {
        return this.mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customizeinfo (");

        sb.append(id);
        sb.append(", ").append(productsize);
        sb.append(", ").append(count);
        sb.append(", ").append(customizeproductid);
        sb.append(", ").append(createtime);
        sb.append(", ").append(searchdate);
        sb.append(", ").append(mark);

        sb.append(")");
        return sb.toString();
    }
}
