/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Imagehashcodecache implements Serializable {

    private static final long serialVersionUID = -642132942;

    private String hashcode;
    private String productid;
    private String categoryId;

    public Imagehashcodecache() {}

    public Imagehashcodecache(Imagehashcodecache value) {
        this.hashcode = value.hashcode;
        this.productid = value.productid;
        this.categoryId = value.categoryId;
    }

    public Imagehashcodecache(
        String hashcode,
        String productid,
        String categoryId
    ) {
        this.hashcode = hashcode;
        this.productid = productid;
        this.categoryId = categoryId;
    }

    public String getHashcode() {
        return this.hashcode;
    }

    public void setHashcode(String hashcode) {
        this.hashcode = hashcode;
    }

    public String getProductid() {
        return this.productid;
    }

    public void setProductid(String productid) {
        this.productid = productid;
    }

    public String getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Imagehashcodecache (");

        sb.append(hashcode);
        sb.append(", ").append(productid);
        sb.append(", ").append(categoryId);

        sb.append(")");
        return sb.toString();
    }
}
