/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductBoostTemplateProduct implements Serializable {

    private static final long serialVersionUID = -8137529;

    private String    id;
    private String    productId;
    private Double    amount;
    private Boolean   permanentCycle;
    private String    authCode;
    private Timestamp createDate;
    private Boolean   enable;

    public ProductBoostTemplateProduct() {}

    public ProductBoostTemplateProduct(ProductBoostTemplateProduct value) {
        this.id = value.id;
        this.productId = value.productId;
        this.amount = value.amount;
        this.permanentCycle = value.permanentCycle;
        this.authCode = value.authCode;
        this.createDate = value.createDate;
        this.enable = value.enable;
    }

    public ProductBoostTemplateProduct(
        String    id,
        String    productId,
        Double    amount,
        Boolean   permanentCycle,
        String    authCode,
        Timestamp createDate,
        Boolean   enable
    ) {
        this.id = id;
        this.productId = productId;
        this.amount = amount;
        this.permanentCycle = permanentCycle;
        this.authCode = authCode;
        this.createDate = createDate;
        this.enable = enable;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Boolean getPermanentCycle() {
        return this.permanentCycle;
    }

    public void setPermanentCycle(Boolean permanentCycle) {
        this.permanentCycle = permanentCycle;
    }

    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public Boolean getEnable() {
        return this.enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductBoostTemplateProduct (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(amount);
        sb.append(", ").append(permanentCycle);
        sb.append(", ").append(authCode);
        sb.append(", ").append(createDate);
        sb.append(", ").append(enable);

        sb.append(")");
        return sb.toString();
    }
}
