/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRanking implements Serializable {

    private static final long serialVersionUID = -1499758857;

    private String    productDataId;
    private String    categoryId;
    private String    search;
    private Timestamp createdate;
    private Integer   ranking;

    public ProductRanking() {}

    public ProductRanking(ProductRanking value) {
        this.productDataId = value.productDataId;
        this.categoryId = value.categoryId;
        this.search = value.search;
        this.createdate = value.createdate;
        this.ranking = value.ranking;
    }

    public ProductRanking(
        String    productDataId,
        String    categoryId,
        String    search,
        Timestamp createdate,
        Integer   ranking
    ) {
        this.productDataId = productDataId;
        this.categoryId = categoryId;
        this.search = search;
        this.createdate = createdate;
        this.ranking = ranking;
    }

    public String getProductDataId() {
        return this.productDataId;
    }

    public void setProductDataId(String productDataId) {
        this.productDataId = productDataId;
    }

    public String getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getSearch() {
        return this.search;
    }

    public void setSearch(String search) {
        this.search = search;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    public Integer getRanking() {
        return this.ranking;
    }

    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductRanking (");

        sb.append(productDataId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(search);
        sb.append(", ").append(createdate);
        sb.append(", ").append(ranking);

        sb.append(")");
        return sb.toString();
    }
}
