/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkuImage implements Serializable {

    private static final long serialVersionUID = -397888249;

    private String id;
    private String url;
    private String parentsku;
    private Date   createdate;
    private Long   filesize;
    private String userid;
    private String taskrecordid;

    public SkuImage() {}

    public SkuImage(SkuImage value) {
        this.id = value.id;
        this.url = value.url;
        this.parentsku = value.parentsku;
        this.createdate = value.createdate;
        this.filesize = value.filesize;
        this.userid = value.userid;
        this.taskrecordid = value.taskrecordid;
    }

    public SkuImage(
        String id,
        String url,
        String parentsku,
        Date   createdate,
        Long   filesize,
        String userid,
        String taskrecordid
    ) {
        this.id = id;
        this.url = url;
        this.parentsku = parentsku;
        this.createdate = createdate;
        this.filesize = filesize;
        this.userid = userid;
        this.taskrecordid = taskrecordid;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getParentsku() {
        return this.parentsku;
    }

    public void setParentsku(String parentsku) {
        this.parentsku = parentsku;
    }

    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public Long getFilesize() {
        return this.filesize;
    }

    public void setFilesize(Long filesize) {
        this.filesize = filesize;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getTaskrecordid() {
        return this.taskrecordid;
    }

    public void setTaskrecordid(String taskrecordid) {
        this.taskrecordid = taskrecordid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SkuImage (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(parentsku);
        sb.append(", ").append(createdate);
        sb.append(", ").append(filesize);
        sb.append(", ").append(userid);
        sb.append(", ").append(taskrecordid);

        sb.append(")");
        return sb.toString();
    }
}
