/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taskrecord implements Serializable {

    private static final long serialVersionUID = -1827555914;

    private String    id;
    private String    fiilename;
    private String    newfilename;
    private Timestamp createdata;
    private String    userid;

    public Taskrecord() {}

    public Taskrecord(Taskrecord value) {
        this.id = value.id;
        this.fiilename = value.fiilename;
        this.newfilename = value.newfilename;
        this.createdata = value.createdata;
        this.userid = value.userid;
    }

    public Taskrecord(
        String    id,
        String    fiilename,
        String    newfilename,
        Timestamp createdata,
        String    userid
    ) {
        this.id = id;
        this.fiilename = fiilename;
        this.newfilename = newfilename;
        this.createdata = createdata;
        this.userid = userid;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFiilename() {
        return this.fiilename;
    }

    public void setFiilename(String fiilename) {
        this.fiilename = fiilename;
    }

    public String getNewfilename() {
        return this.newfilename;
    }

    public void setNewfilename(String newfilename) {
        this.newfilename = newfilename;
    }

    public Timestamp getCreatedata() {
        return this.createdata;
    }

    public void setCreatedata(Timestamp createdata) {
        this.createdata = createdata;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Taskrecord (");

        sb.append(id);
        sb.append(", ").append(fiilename);
        sb.append(", ").append(newfilename);
        sb.append(", ").append(createdata);
        sb.append(", ").append(userid);

        sb.append(")");
        return sb.toString();
    }
}
