/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishProductSalesMonitorData implements Serializable {

    private static final long serialVersionUID = 810262946;

    private String    id;
    private String    authCode;
    private String    productId;
    private String    mainImage;
    private String    parentSku;
    private String    variantSku;
    private String    variantId;
    private Double    price;
    private Double    shipping;
    private String    localizedCurrencyCode;
    private String    size;
    private String    color;
    private Double    localizedPrice;
    private Double    localizedShipping;
    private Timestamp dateUploaded;
    private Boolean   inventoryStatus;
    private Integer   inventoryChange;
    private Timestamp createDate;
    private Integer   numberSold;
    private Integer   numberSaves;

    public WishProductSalesMonitorData() {}

    public WishProductSalesMonitorData(WishProductSalesMonitorData value) {
        this.id = value.id;
        this.authCode = value.authCode;
        this.productId = value.productId;
        this.mainImage = value.mainImage;
        this.parentSku = value.parentSku;
        this.variantSku = value.variantSku;
        this.variantId = value.variantId;
        this.price = value.price;
        this.shipping = value.shipping;
        this.localizedCurrencyCode = value.localizedCurrencyCode;
        this.size = value.size;
        this.color = value.color;
        this.localizedPrice = value.localizedPrice;
        this.localizedShipping = value.localizedShipping;
        this.dateUploaded = value.dateUploaded;
        this.inventoryStatus = value.inventoryStatus;
        this.inventoryChange = value.inventoryChange;
        this.createDate = value.createDate;
        this.numberSold = value.numberSold;
        this.numberSaves = value.numberSaves;
    }

    public WishProductSalesMonitorData(
        String    id,
        String    authCode,
        String    productId,
        String    mainImage,
        String    parentSku,
        String    variantSku,
        String    variantId,
        Double    price,
        Double    shipping,
        String    localizedCurrencyCode,
        String    size,
        String    color,
        Double    localizedPrice,
        Double    localizedShipping,
        Timestamp dateUploaded,
        Boolean   inventoryStatus,
        Integer   inventoryChange,
        Timestamp createDate,
        Integer   numberSold,
        Integer   numberSaves
    ) {
        this.id = id;
        this.authCode = authCode;
        this.productId = productId;
        this.mainImage = mainImage;
        this.parentSku = parentSku;
        this.variantSku = variantSku;
        this.variantId = variantId;
        this.price = price;
        this.shipping = shipping;
        this.localizedCurrencyCode = localizedCurrencyCode;
        this.size = size;
        this.color = color;
        this.localizedPrice = localizedPrice;
        this.localizedShipping = localizedShipping;
        this.dateUploaded = dateUploaded;
        this.inventoryStatus = inventoryStatus;
        this.inventoryChange = inventoryChange;
        this.createDate = createDate;
        this.numberSold = numberSold;
        this.numberSaves = numberSaves;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getMainImage() {
        return this.mainImage;
    }

    public void setMainImage(String mainImage) {
        this.mainImage = mainImage;
    }

    public String getParentSku() {
        return this.parentSku;
    }

    public void setParentSku(String parentSku) {
        this.parentSku = parentSku;
    }

    public String getVariantSku() {
        return this.variantSku;
    }

    public void setVariantSku(String variantSku) {
        this.variantSku = variantSku;
    }

    public String getVariantId() {
        return this.variantId;
    }

    public void setVariantId(String variantId) {
        this.variantId = variantId;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getShipping() {
        return this.shipping;
    }

    public void setShipping(Double shipping) {
        this.shipping = shipping;
    }

    public String getLocalizedCurrencyCode() {
        return this.localizedCurrencyCode;
    }

    public void setLocalizedCurrencyCode(String localizedCurrencyCode) {
        this.localizedCurrencyCode = localizedCurrencyCode;
    }

    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Double getLocalizedPrice() {
        return this.localizedPrice;
    }

    public void setLocalizedPrice(Double localizedPrice) {
        this.localizedPrice = localizedPrice;
    }

    public Double getLocalizedShipping() {
        return this.localizedShipping;
    }

    public void setLocalizedShipping(Double localizedShipping) {
        this.localizedShipping = localizedShipping;
    }

    public Timestamp getDateUploaded() {
        return this.dateUploaded;
    }

    public void setDateUploaded(Timestamp dateUploaded) {
        this.dateUploaded = dateUploaded;
    }

    public Boolean getInventoryStatus() {
        return this.inventoryStatus;
    }

    public void setInventoryStatus(Boolean inventoryStatus) {
        this.inventoryStatus = inventoryStatus;
    }

    public Integer getInventoryChange() {
        return this.inventoryChange;
    }

    public void setInventoryChange(Integer inventoryChange) {
        this.inventoryChange = inventoryChange;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public Integer getNumberSold() {
        return this.numberSold;
    }

    public void setNumberSold(Integer numberSold) {
        this.numberSold = numberSold;
    }

    public Integer getNumberSaves() {
        return this.numberSaves;
    }

    public void setNumberSaves(Integer numberSaves) {
        this.numberSaves = numberSaves;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WishProductSalesMonitorData (");

        sb.append(id);
        sb.append(", ").append(authCode);
        sb.append(", ").append(productId);
        sb.append(", ").append(mainImage);
        sb.append(", ").append(parentSku);
        sb.append(", ").append(variantSku);
        sb.append(", ").append(variantId);
        sb.append(", ").append(price);
        sb.append(", ").append(shipping);
        sb.append(", ").append(localizedCurrencyCode);
        sb.append(", ").append(size);
        sb.append(", ").append(color);
        sb.append(", ").append(localizedPrice);
        sb.append(", ").append(localizedShipping);
        sb.append(", ").append(dateUploaded);
        sb.append(", ").append(inventoryStatus);
        sb.append(", ").append(inventoryChange);
        sb.append(", ").append(createDate);
        sb.append(", ").append(numberSold);
        sb.append(", ").append(numberSaves);

        sb.append(")");
        return sb.toString();
    }
}
