/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishProduct implements Serializable {

    private static final long serialVersionUID = -1542782242;

    private String    id;
    private String    mainImage;
    private String    name;
    private String    extraImages;
    private Integer   numberSaves;
    private Integer   numberSold;
    private String    parentSku;
    private Timestamp dateUploaded;
    private String    description;
    private String    tags;
    private String    countryShippings;
    private String    authcode;
    private Timestamp createDate;

    public WishProduct() {}

    public WishProduct(WishProduct value) {
        this.id = value.id;
        this.mainImage = value.mainImage;
        this.name = value.name;
        this.extraImages = value.extraImages;
        this.numberSaves = value.numberSaves;
        this.numberSold = value.numberSold;
        this.parentSku = value.parentSku;
        this.dateUploaded = value.dateUploaded;
        this.description = value.description;
        this.tags = value.tags;
        this.countryShippings = value.countryShippings;
        this.authcode = value.authcode;
        this.createDate = value.createDate;
    }

    public WishProduct(
        String    id,
        String    mainImage,
        String    name,
        String    extraImages,
        Integer   numberSaves,
        Integer   numberSold,
        String    parentSku,
        Timestamp dateUploaded,
        String    description,
        String    tags,
        String    countryShippings,
        String    authcode,
        Timestamp createDate
    ) {
        this.id = id;
        this.mainImage = mainImage;
        this.name = name;
        this.extraImages = extraImages;
        this.numberSaves = numberSaves;
        this.numberSold = numberSold;
        this.parentSku = parentSku;
        this.dateUploaded = dateUploaded;
        this.description = description;
        this.tags = tags;
        this.countryShippings = countryShippings;
        this.authcode = authcode;
        this.createDate = createDate;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMainImage() {
        return this.mainImage;
    }

    public void setMainImage(String mainImage) {
        this.mainImage = mainImage;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getExtraImages() {
        return this.extraImages;
    }

    public void setExtraImages(String extraImages) {
        this.extraImages = extraImages;
    }

    public Integer getNumberSaves() {
        return this.numberSaves;
    }

    public void setNumberSaves(Integer numberSaves) {
        this.numberSaves = numberSaves;
    }

    public Integer getNumberSold() {
        return this.numberSold;
    }

    public void setNumberSold(Integer numberSold) {
        this.numberSold = numberSold;
    }

    public String getParentSku() {
        return this.parentSku;
    }

    public void setParentSku(String parentSku) {
        this.parentSku = parentSku;
    }

    public Timestamp getDateUploaded() {
        return this.dateUploaded;
    }

    public void setDateUploaded(Timestamp dateUploaded) {
        this.dateUploaded = dateUploaded;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTags() {
        return this.tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getCountryShippings() {
        return this.countryShippings;
    }

    public void setCountryShippings(String countryShippings) {
        this.countryShippings = countryShippings;
    }

    public String getAuthcode() {
        return this.authcode;
    }

    public void setAuthcode(String authcode) {
        this.authcode = authcode;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WishProduct (");

        sb.append(id);
        sb.append(", ").append(mainImage);
        sb.append(", ").append(name);
        sb.append(", ").append(extraImages);
        sb.append(", ").append(numberSaves);
        sb.append(", ").append(numberSold);
        sb.append(", ").append(parentSku);
        sb.append(", ").append(dateUploaded);
        sb.append(", ").append(description);
        sb.append(", ").append(tags);
        sb.append(", ").append(countryShippings);
        sb.append(", ").append(authcode);
        sb.append(", ").append(createDate);

        sb.append(")");
        return sb.toString();
    }
}
