/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishSoldDate implements Serializable {

    private static final long serialVersionUID = -314452065;

    private String  id;
    private String  date;
    private Integer sort;

    public WishSoldDate() {}

    public WishSoldDate(WishSoldDate value) {
        this.id = value.id;
        this.date = value.date;
        this.sort = value.sort;
    }

    public WishSoldDate(
        String  id,
        String  date,
        Integer sort
    ) {
        this.id = id;
        this.date = date;
        this.sort = sort;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WishSoldDate (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(sort);

        sb.append(")");
        return sb.toString();
    }
}
