/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishProductNumberSold implements Serializable {

    private static final long serialVersionUID = 1930156740;

    private String    id;
    private String    productId;
    private Integer   numbersold;
    private Integer   numbersaves;
    private Timestamp createdate;
    private String    searchdate;
    private String    soldDateId;
    private Timestamp dateUploaded;

    public WishProductNumberSold() {}

    public WishProductNumberSold(WishProductNumberSold value) {
        this.id = value.id;
        this.productId = value.productId;
        this.numbersold = value.numbersold;
        this.numbersaves = value.numbersaves;
        this.createdate = value.createdate;
        this.searchdate = value.searchdate;
        this.soldDateId = value.soldDateId;
        this.dateUploaded = value.dateUploaded;
    }

    public WishProductNumberSold(
        String    id,
        String    productId,
        Integer   numbersold,
        Integer   numbersaves,
        Timestamp createdate,
        String    searchdate,
        String    soldDateId,
        Timestamp dateUploaded
    ) {
        this.id = id;
        this.productId = productId;
        this.numbersold = numbersold;
        this.numbersaves = numbersaves;
        this.createdate = createdate;
        this.searchdate = searchdate;
        this.soldDateId = soldDateId;
        this.dateUploaded = dateUploaded;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public Integer getNumbersold() {
        return this.numbersold;
    }

    public void setNumbersold(Integer numbersold) {
        this.numbersold = numbersold;
    }

    public Integer getNumbersaves() {
        return this.numbersaves;
    }

    public void setNumbersaves(Integer numbersaves) {
        this.numbersaves = numbersaves;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    public String getSearchdate() {
        return this.searchdate;
    }

    public void setSearchdate(String searchdate) {
        this.searchdate = searchdate;
    }

    public String getSoldDateId() {
        return this.soldDateId;
    }

    public void setSoldDateId(String soldDateId) {
        this.soldDateId = soldDateId;
    }

    public Timestamp getDateUploaded() {
        return this.dateUploaded;
    }

    public void setDateUploaded(Timestamp dateUploaded) {
        this.dateUploaded = dateUploaded;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WishProductNumberSold (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(numbersold);
        sb.append(", ").append(numbersaves);
        sb.append(", ").append(createdate);
        sb.append(", ").append(searchdate);
        sb.append(", ").append(soldDateId);
        sb.append(", ").append(dateUploaded);

        sb.append(")");
        return sb.toString();
    }
}
