/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishCvsRecord implements Serializable {

    private static final long serialVersionUID = -843024547;

    private String    jobId;
    private String    accessToken;
    private String    type;
    private String    authCode;
    private Timestamp createDate;
    private String    filepath;

    public WishCvsRecord() {}

    public WishCvsRecord(WishCvsRecord value) {
        this.jobId = value.jobId;
        this.accessToken = value.accessToken;
        this.type = value.type;
        this.authCode = value.authCode;
        this.createDate = value.createDate;
        this.filepath = value.filepath;
    }

    public WishCvsRecord(
        String    jobId,
        String    accessToken,
        String    type,
        String    authCode,
        Timestamp createDate,
        String    filepath
    ) {
        this.jobId = jobId;
        this.accessToken = accessToken;
        this.type = type;
        this.authCode = authCode;
        this.createDate = createDate;
        this.filepath = filepath;
    }

    public String getJobId() {
        return this.jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public String getAccessToken() {
        return this.accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getFilepath() {
        return this.filepath;
    }

    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WishCvsRecord (");

        sb.append(jobId);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(type);
        sb.append(", ").append(authCode);
        sb.append(", ").append(createDate);
        sb.append(", ").append(filepath);

        sb.append(")");
        return sb.toString();
    }
}
