/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishCategory implements Serializable {

    private static final long serialVersionUID = -1908581044;

    private String    id;
    private String    categoryname;
    private String    search;
    private Timestamp createdate;
    private String    collectionSwitch;

    public WishCategory() {}

    public WishCategory(WishCategory value) {
        this.id = value.id;
        this.categoryname = value.categoryname;
        this.search = value.search;
        this.createdate = value.createdate;
        this.collectionSwitch = value.collectionSwitch;
    }

    public WishCategory(
        String    id,
        String    categoryname,
        String    search,
        Timestamp createdate,
        String    collectionSwitch
    ) {
        this.id = id;
        this.categoryname = categoryname;
        this.search = search;
        this.createdate = createdate;
        this.collectionSwitch = collectionSwitch;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCategoryname() {
        return this.categoryname;
    }

    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    public String getSearch() {
        return this.search;
    }

    public void setSearch(String search) {
        this.search = search;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    public String getCollectionSwitch() {
        return this.collectionSwitch;
    }

    public void setCollectionSwitch(String collectionSwitch) {
        this.collectionSwitch = collectionSwitch;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WishCategory (");

        sb.append(id);
        sb.append(", ").append(categoryname);
        sb.append(", ").append(search);
        sb.append(", ").append(createdate);
        sb.append(", ").append(collectionSwitch);

        sb.append(")");
        return sb.toString();
    }
}
