/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.wish.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WishKeywordSearch implements Serializable {

    private static final long serialVersionUID = -925102694;

    private String id;
    private String cookie;
    private String accessToken;

    public WishKeywordSearch() {}

    public WishKeywordSearch(WishKeywordSearch value) {
        this.id = value.id;
        this.cookie = value.cookie;
        this.accessToken = value.accessToken;
    }

    public WishKeywordSearch(
        String id,
        String cookie,
        String accessToken
    ) {
        this.id = id;
        this.cookie = cookie;
        this.accessToken = accessToken;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCookie() {
        return this.cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    public String getAccessToken() {
        return this.accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WishKeywordSearch (");

        sb.append(id);
        sb.append(", ").append(cookie);
        sb.append(", ").append(accessToken);

        sb.append(")");
        return sb.toString();
    }
}
