/*
 * This file is generated by jOOQ.
*/
package tanggod.github.io.config.database.repository.system.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Binding implements Serializable {

    private static final long serialVersionUID = 607405239;

    private String    id;
    private String    systemProductId;
    private String    systemVariationId;
    private String    platformProductId;
    private String    platformVariationId;
    private String    platformName;
    private Timestamp createDate;
    private Timestamp updateDate;
    private String    systemVariationSkuName;
    private String    platformVariationSkuName;
    private String    authCode;

    public Binding() {}

    public Binding(Binding value) {
        this.id = value.id;
        this.systemProductId = value.systemProductId;
        this.systemVariationId = value.systemVariationId;
        this.platformProductId = value.platformProductId;
        this.platformVariationId = value.platformVariationId;
        this.platformName = value.platformName;
        this.createDate = value.createDate;
        this.updateDate = value.updateDate;
        this.systemVariationSkuName = value.systemVariationSkuName;
        this.platformVariationSkuName = value.platformVariationSkuName;
        this.authCode = value.authCode;
    }

    public Binding(
        String    id,
        String    systemProductId,
        String    systemVariationId,
        String    platformProductId,
        String    platformVariationId,
        String    platformName,
        Timestamp createDate,
        Timestamp updateDate,
        String    systemVariationSkuName,
        String    platformVariationSkuName,
        String    authCode
    ) {
        this.id = id;
        this.systemProductId = systemProductId;
        this.systemVariationId = systemVariationId;
        this.platformProductId = platformProductId;
        this.platformVariationId = platformVariationId;
        this.platformName = platformName;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.systemVariationSkuName = systemVariationSkuName;
        this.platformVariationSkuName = platformVariationSkuName;
        this.authCode = authCode;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSystemProductId() {
        return this.systemProductId;
    }

    public void setSystemProductId(String systemProductId) {
        this.systemProductId = systemProductId;
    }

    public String getSystemVariationId() {
        return this.systemVariationId;
    }

    public void setSystemVariationId(String systemVariationId) {
        this.systemVariationId = systemVariationId;
    }

    public String getPlatformProductId() {
        return this.platformProductId;
    }

    public void setPlatformProductId(String platformProductId) {
        this.platformProductId = platformProductId;
    }

    public String getPlatformVariationId() {
        return this.platformVariationId;
    }

    public void setPlatformVariationId(String platformVariationId) {
        this.platformVariationId = platformVariationId;
    }

    public String getPlatformName() {
        return this.platformName;
    }

    public void setPlatformName(String platformName) {
        this.platformName = platformName;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    public String getSystemVariationSkuName() {
        return this.systemVariationSkuName;
    }

    public void setSystemVariationSkuName(String systemVariationSkuName) {
        this.systemVariationSkuName = systemVariationSkuName;
    }

    public String getPlatformVariationSkuName() {
        return this.platformVariationSkuName;
    }

    public void setPlatformVariationSkuName(String platformVariationSkuName) {
        this.platformVariationSkuName = platformVariationSkuName;
    }

    public String getAuthCode() {
        return this.authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Binding (");

        sb.append(id);
        sb.append(", ").append(systemProductId);
        sb.append(", ").append(systemVariationId);
        sb.append(", ").append(platformProductId);
        sb.append(", ").append(platformVariationId);
        sb.append(", ").append(platformName);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(systemVariationSkuName);
        sb.append(", ").append(platformVariationSkuName);
        sb.append(", ").append(authCode);

        sb.append(")");
        return sb.toString();
    }
}
